"""Copy-ready literature reviews for every forecasting method.

These reviews complement the shorter audited overviews in ``method_info.py``.  They
use only the primary or method-defining works listed in each method's APA reference
list, so an exported note remains internally consistent and ready for scholarly use.
"""

from __future__ import annotations


METHOD_LITERATURE_REVIEWS: dict[str, str] = {
    "naive": """
The naive or persistence forecast sets every future point forecast equal to the latest observed value. Its stochastic foundation is the random walk, terminology introduced by Pearson (1905) while posing a probability problem about successive independent movements. The familiar time-series model writes the next level as the current level plus an unpredictable innovation. If those innovations have zero conditional mean, the current observation is the conditional-mean forecast of every later level; under a median-zero assumption it is likewise a conditional-median forecast. This connection matters because the naive rule is not merely an arbitrary shortcut. It is the optimal point forecast for a specific and important data-generating process, even though fitting Chrono Stream's rule does not claim that the complete random-walk distribution has been established.

Hyndman and Athanasopoulos (2021) define the modern forecasting equation y-hat(T+h|T)=y(T) and emphasize simple methods as benchmarks. The historical one-step fitted value at t is y(t-1), so the residuals are first differences. The method estimates no slope, seasonal state, or smoothing coefficient and its point path remains flat until a new observation arrives. This parsimony makes it hard to beat for highly persistent series, asset-like levels, and short horizons. It also gives model comparison an interpretable reference: added machinery should earn its cost through genuine chronological holdout improvement, not merely a closer in-sample fit. Hyndman and Koehler (2006) reinforce this role by using naive errors in scale-free accuracy measures and examining why common percentage metrics can mislead.

Chrono Stream fits persistence once on the pre-holdout observations and again on the complete data for the future forecast. It reports the final value and labels the multi-step rule as direct persistence. Fitted values use only the preceding observation, preventing look-ahead. Its Gaussian random-walk interval estimates innovation variance from first differences and accumulates forecast standard deviation as sqrt(h); the nominal coverage therefore depends on independent, constant-variance Gaussian innovations. Persistence cannot anticipate trend, seasonality, intervention effects, mean reversion, or turning points. Those limitations are precisely why it is useful: failure to outperform such a transparent rule is evidence that a more elaborate method has not extracted stable additional signal from the available history.
""".strip(),
    "seasonal_naive": """
Seasonal naive forecasting applies persistence separately to each position in a repeating cycle. Rather than carrying the final value across every horizon, it assigns a future January the latest observed January, a future Monday the latest observed Monday, or more generally uses the latest value with the same phase modulo the seasonal period. No single publication can responsibly be named as the inventor of this elementary rule. Hyndman and Athanasopoulos (2021) provide a precise modern formulation: for period m, each h-step forecast reaches backward by enough complete cycles to select the most recent observed value in the matching season. That definition makes the method causal and distinguishes it from centered seasonal smoothers that require future observations.

The rule is both simple and demanding about data semantics. Observations must be regularly spaced, the integer period must represent a real recurring cycle, and the phase alignment must be correct. Historical one-step fitted values begin only after one complete period and equal y(t-m). Future horizons repeat the last observed cycle directly, including horizons beyond m. Hyndman and Koehler (2006) use errors from naive or seasonal-naive forecasts to scale forecast accuracy, demonstrating why these rules are more than visual conveniences: they provide series-relative denominators and defensible baselines. Large empirical exercises such as the M3 competition described by Makridakis and Hibon (2000) similarly show why simple benchmarks must remain present when evaluating sophisticated forecasting systems.

Chrono Stream requires a period of at least two and two complete observed cycles, fits the rule independently before the holdout and on the full series, and records the selected period in result metadata. No holdout value is allowed to populate the evaluation cycle. The point forecast is a direct seasonal repetition, not recursive estimation. Its Gaussian seasonal-random-walk interval estimates variance from seasonal differences and accumulates uncertainty after each additional complete forecast cycle; nominal coverage depends on independent, constant-variance Gaussian seasonal innovations. Seasonal persistence is often competitive when the within-cycle pattern is stable, but it cannot model trend, moving holidays, phase shifts, changing amplitude, multiple seasonalities, or structural breaks. Users should compare it with a nonseasonal naive forecast to learn whether seasonal alignment adds value and should not infer a stable seasonal mechanism merely because one held-out cycle happens to be predicted well.
""".strip(),
    "drift": """
The drift forecast extends persistence by allowing the random walk to have a nonzero mean increment. Pearson's (1905) random-walk problem supplies the historical probabilistic lineage, while Hyndman and Athanasopoulos (2021) give the forecasting rule used in modern practice. With observations y(1),...,y(n), the estimated increment is [y(n)-y(1)]/(n-1). This expression equals the arithmetic mean of the successive first differences because their sum telescopes to the endpoint difference. The h-step forecast is y(n)+h times that increment. It is therefore a random-walk-with-drift benchmark, not the same estimator as ordinary least-squares regression of every observed level on time.

The distinction from linear trend projection is substantive. A least-squares line uses all levels to choose an intercept and slope that minimize squared vertical deviations. The drift estimate uses the first and last levels to recover the mean of the observed increments and anchors every forecast at the latest value. Interior observations affect residual behavior but cancel from the point-estimate formula. This produces a transparent trend-sensitive comparison for the flat naive forecast, yet it also creates strong endpoint sensitivity. A temporary initial trough or terminal spike can tilt the entire future path. Makridakis and Hibon (2000) document the importance of retaining simple reference methods in large empirical comparisons; complexity cannot be presumed superior without out-of-sample evidence.

Chrono Stream estimates drift only from the current training partition during holdout evaluation, then re-estimates it independently from the complete series for future forecasting. Result details record both endpoints, the per-step increment, and the direct multi-horizon strategy. Historical fitted values are one-step forecasts y(t-1)+c rather than points on the endpoint line. Its Gaussian random-walk-with-drift interval uses forecast variance sigma-squared times h(1+h/(T-1)), accounting for accumulated innovations and estimation of c. Drift can be useful for short horizons when average change is reasonably stable, but it ignores seasonality, curvature, interventions, saturation, mean reversion, and external regressors. Its uncertainty and endpoint sensitivity grow in practical importance with horizon, so it should be treated as an essential comparator rather than a permanent-growth law.
""".strip(),
    "moving_average": """
Moving averages belong to the earliest formal tools for separating persistent movement from short-run fluctuation in ordered observations. Poynting (1884) compared successive averages in an economic time series, while Hooker (1901) explicitly used a nine-year moving average to distinguish longer movement from annual variation. These contributions predate modern stochastic forecasting theory; their original purpose was primarily descriptive smoothing. Macaulay (1931) later gave a systematic treatment of moving-average graduation, including the effect of span and weights on the smoothness and timing of the resulting series. The literature therefore supports a careful historical claim: no single paper invented every use now called a “moving average,” but these works document the transition from informal averaging to an explicit time-series filter.

For a trailing simple moving average of span w, the one-step forecast is the arithmetic mean of the most recent w observations. This is a finite-impulse-response low-pass filter: short oscillations tend to cancel, while persistent local level is retained. The span controls the bias–variance trade-off. A short window responds rapidly but transmits noise; a long window is smoother but reacts slowly to level changes. Centered moving averages are useful for decomposition but require future observations and therefore cannot be used directly for real-time forecasting. A trailing average is causal, although repeated multi-step forecasting requires an additional convention because future windows contain values that have not yet been observed.

As a forecasting model, the simple moving average is most defensible as a transparent local-level benchmark. It assumes that observations within the chosen window are exchangeable enough for their mean to represent the next level, gives every included observation identical influence, and discards all earlier observations abruptly. It contains no explicit trend, seasonal, intervention, or probabilistic error component. These limitations explain why moving averages remain useful for baselines and exploratory smoothing but are rarely sufficient for series with sustained trend or recurring seasonality. Chrono Stream implements a causal trailing average, searches candidate spans by one-step-ahead training RMSE when automatic selection is enabled, and recursively inserts forecasts for horizons beyond one step. That recursive convention is operationally coherent, but uncertainty can compound and the selected in-sample span should still be checked on held-out or rolling-origin data.
""".strip(),
    "weighted_moving_average": """
Weighted moving averages developed from the broader problem of graduating noisy ordered data while retaining important shape. Spencer (1904) proposed an explicit set of unequal finite weights for smoothing sickness and mortality rates, and Henderson (1916) developed adjusted-average weights designed to reproduce local polynomial movement while suppressing irregular variation. Macaulay (1931) subsequently organized simple and weighted moving-average methods and showed that weighting is a filter-design decision rather than a cosmetic variation on averaging. These sources establish the method as a family of linear filters: the phrase “weighted moving average” does not identify one universal set of weights.

Given a window of w observations and normalized weights a_1,...,a_w, the forecast is the linear combination sum(a_i y_i), where the weights sum to one. Increasing weights toward the most recent observation produces a causal recency-weighted forecast; symmetric weights instead suit retrospective smoothing but are unavailable at a live endpoint. Weight shape determines response. Linear recency weights decline at a constant step, whereas exponential weights decline geometrically inside the finite window. Unlike simple exponential smoothing, however, a finite weighted moving average drops an observation completely once it leaves the window and need not arise from a stochastic state-space model.

The approach is useful when substantive knowledge says that recent values are more informative and when interpretability matters more than a rich data-generating model. Its performance depends jointly on window length and weight profile. Too much recency emphasis follows noise; too little adapts slowly to structural change. Fixed weights do not estimate trend, seasonality, nonlinear response, or conditional variance, and recursive multi-step use substitutes predictions for observations. Chrono Stream offers linear or exponential recency patterns, normalizes the weights, and can select the window by one-step-ahead training RMSE. This implementation is a pragmatic forecast filter rather than the symmetric Spencer or Henderson graduation formula itself; those historical papers establish the weighted-filter tradition, not the app's exact modern weight presets. External validation remains important because optimizing a window on the same series can favor an overly responsive specification.
""".strip(),
    "single_exponential_smoothing": """
Single exponential smoothing (SES) emerged as a forecasting method for series whose local level changes gradually but that lack a persistent trend or seasonal cycle. Brown (1956) provided an early widely documented demand-forecasting treatment, and Holt's 1957 report, later reprinted as Holt (2004), placed exponentially weighted level updates within a broader family that could also represent trend and seasonality. Muth (1960) supplied the key statistical justification: under an appropriate local-level process, an exponentially weighted forecast has optimal properties. Thus, SES is more than an arbitrary recency rule; it can be interpreted both as a forecasting recursion and as the optimal filter for a particular stochastic model.

The level update is l_t = alpha*y_t + (1-alpha)l_(t-1), with 0 < alpha <= 1, and every future point forecast equals the final estimated level when no trend is included. Expanding the recursion shows geometrically declining weights on older observations plus an initialization term. Large alpha values adapt quickly but produce a variable level estimate; small values smooth strongly but lag after shifts. This infinite geometric memory distinguishes SES from a finite weighted moving average. Estimation ordinarily chooses alpha and the initial state by minimizing a likelihood or squared-error objective instead of treating alpha as a universal constant.

SES is appropriate for short-horizon forecasts of a noisy, nonseasonal level and provides a strong benchmark because it is parsimonious, adaptive, and interpretable. It is misspecified when trend or seasonality is systematic, and its constant point forecast should not be mistaken for an assertion that the actual series will be flat. Forecast uncertainty grows with horizon even though the point forecast does not change. Chrono Stream uses the statsmodels simple-exponential-smoothing implementation, either estimates alpha automatically or accepts a user value, and reports the fitted level recursion. The historical and optimality literature supports that implementation, while also implying a practical model-selection rule: visible trend calls for Holt's method and stable repeating seasonality calls for a seasonal extension rather than an artificially large smoothing coefficient.
""".strip(),
    "double_exponential_smoothing": """
Holt's linear trend method extends exponential smoothing from a changing level to a changing level plus slope. Holt developed the coupled recursions in a 1957 research memorandum reprinted as Holt (2004), allowing trend to be updated rather than imposed by a global regression line. Winters (1960) built on this system for seasonal sales forecasting, helping establish the level–trend–seasonal family now associated with the two authors. Gardner and McKenzie (1985) later introduced and studied a damped-trend form in which the long-horizon extrapolated slope is progressively reduced. The literature therefore distinguishes ordinary Holt, which projects a linear trend indefinitely, from damped Holt, which allows near-term trend but limits distant extrapolation.

In the additive-trend formulation, the level combines the current observation with the previous level advanced by the previous trend, while the trend smooths the change between successive levels. The h-step point forecast is l_t + h*b_t for an undamped trend. With damping parameter phi between zero and one, the accumulated future trend becomes a finite geometric sum, so forecasts eventually approach an asymptote in their increments. Smoothing parameters govern how quickly level and slope respond, and their estimates are interdependent with initialization. This local recursion differs from least-squares linear trend fitting: a global regression gives all points leverage on one fixed line, whereas Holt continually updates its terminal state.

Holt's method is suitable when a nonseasonal series displays a reasonably smooth trend whose recent direction is informative. Undamped extrapolation can become implausible at long horizons, particularly after a temporary surge, so damping is often a valuable robustness option. The method does not model a repeating seasonal pattern, abrupt interventions, or autoregressive residual structure, and a trend detected over a short sample may not persist. Chrono Stream uses the statsmodels Holt implementation, permits automatic or manual level and trend smoothing, and exposes optional damping. This matches the defining recursions and the Gardner–McKenzie extension; users should compare damped and undamped forecasts out of sample rather than interpret either trajectory as a structural law.
""".strip(),
    "triple_exponential_smoothing": """
Seasonal exponential smoothing arose from extending Holt's evolving level and trend to a recurring seasonal state. Holt's 1957 report, reprinted as Holt (2004), described exponentially weighted forecasting of trends and seasonals, and Winters (1960) presented the sales-forecasting system now commonly called Holt–Winters. Gardner and McKenzie (1985) subsequently developed damping for trend extrapolation, an extension that can also be combined with seasonal exponential smoothing. “Triple exponential smoothing” is therefore a popular label for a component model with level, trend, and seasonality; it should not be confused with applying the same smoothing operation three times.

The method updates three linked states. The level represents the deseasonalized local position, the trend represents its local slope, and seasonal indices represent recurring within-cycle effects. In an additive seasonal form, the seasonal contribution is measured in the units of the series and is added to level and trend. In a multiplicative form, it scales the level and is better suited to seasonal amplitude that grows with the series; it also requires positive, nonzero data. Forecasts advance the terminal level and trend and reuse the seasonal state from the corresponding position in the cycle. The seasonal period is substantive model information, not a parameter that can be inferred reliably from very short data.

Holt–Winters is useful when seasonality is stable enough to repeat and at least two full cycles are available for initialization and estimation. It is vulnerable to incorrect period choice, evolving or multiple seasonalities, calendar effects, outliers, and abrupt level changes. Multiplicative seasonality can be numerically and conceptually inappropriate around zero, while an undamped trend may dominate long-horizon forecasts. Chrono Stream uses statsmodels' additive or multiplicative seasonal Holt–Winters model, supports additive or multiplicative trend and optional damping, and requires sufficient cycles. This is faithful to the level–trend–seasonal tradition, but it is not an automatic guarantee of seasonal adequacy: residual autocorrelation and rolling-origin accuracy should be inspected, especially when the seasonal pattern changes over time.
""".strip(),
    "arima": """
Autoregressive integrated moving-average modeling combines three ideas that developed separately. Yule (1927) constructed autoregressive dependence by relating a value to its own lags, while Slutzky (1937, original work published 1927) showed that finite moving sums of random causes can generate systematic serial patterns. Box and Jenkins (1970) unified autoregression, moving-average errors, differencing, identification, estimation, diagnostic checking, and forecasting into a repeatable modeling strategy. In ARIMA(p,d,q), regular differencing of order d is intended to remove stochastic mean nonstationarity, after which p autoregressive terms and q moving-average innovation terms describe the stationary dependence. This is a stochastic model of conditional means, not merely a curve fitted against time.

Variance stabilization logically precedes mean-stationarity assessment because a changing variance can distort graphical and correlation-based identification. The Box–Cox family was developed by Box and Cox (1964) for positive data, while Yeo and Johnson (2000) provided a related power family that also permits zero and negative values. Both transformations are monotone but nonlinear, so forecasts and interval endpoints must be returned to the data scale deliberately. Chrono Stream fits the transformer only on training data, applies differencing and model estimation on the transformed scale, and uses simulation through the inverse transformation to estimate original-scale means and intervals. This matters because a simple inverse of a transformed conditional mean generally is not the original-scale conditional mean.

Determining d is an inferential decision rather than a mechanical requirement to difference until a plot looks smooth. Dickey and Fuller (1979) established unit-root testing, Phillips and Perron (1988) developed a nonparametric correction for weakly dependent and heteroskedastic disturbances, and Kwiatkowski et al. (1992) reversed the hypotheses by taking stationarity as the null. The opposing nulls make ADF-plus-KPSS a useful triangulation strategy, although neither test proves stationarity and both can have low power or size distortion in short samples, near-unit-root processes, or series with breaks. Chrono Stream lets the user select ADF, KPSS, Phillips–Perron, or an ADF–KPSS consensus and caps differencing to avoid an uncontrolled search.

After transformation and differencing, the ACF and PACF provide Box–Jenkins identification evidence, but their approximate reference bands are guides rather than a unique order-selection theorem. Chrono Stream restores guided, exhaustive, stepwise, and manual order search. Its Stepwise path uses pmdarima's Hyndman–Khandakar-style auto_arima candidate generation (Hyndman & Khandakar, 2008), after which Chrono Stream applies its own disclosed diagnostics and ranking. Other paths construct candidates locally from visible bounds. Candidate fits are ranked with Akaike's information criterion (Akaike, 1974), Schwarz's Bayesian criterion (Schwarz, 1978), Hannan–Quinn (Hannan & Quinn, 1979), small-sample AICc (Hurvich & Tsai, 1989), or expanding-window validation.

Box–Jenkins methodology requires model checking after estimation. Box and Pierce (1970) derived residual-autocorrelation diagnostics, and Ljung and Box (1978) improved the finite-sample approximation of the portmanteau statistic. Chrono Stream additionally offers coefficient Wald z tests, four residual-normality tests (Anderson & Darling, 1952; Jarque & Bera, 1980; Lilliefors, 1967; Shapiro & Wilk, 1965), a zero-mean t test (Student, 1908), Engle's (1982) ARCH LM test, optimizer convergence, and stationarity/invertibility roots. These diagnostics answer different questions and cannot substitute for one another. In particular, failure to reject normality is not proof of Gaussian innovations, while a significant normality test need not invalidate point forecasts. The visible policy choices are strict Box–Jenkins, forecast-oriented, and custom. A strict policy is deliberately demanding: all enabled gates must pass before information criteria rank eligible models, and the user must explicitly authorize a closest-model override if no candidate passes.

ARIMA is most appropriate for a single regularly spaced series whose transformed and differenced dynamics are approximately linear and stable. Its strengths are transparent lag structure, likelihood-based uncertainty, and disciplined residual checking. Its weaknesses include sensitivity to breaks, outliers, missing or irregular timing, excessive differencing, large search spaces, and dependence of intervals on distributional assumptions. A model that passes a battery of tests can still forecast poorly after a regime change, so diagnostic adequacy and rolling-origin predictive performance should be reported together rather than treated as competing definitions of “best.”
""".strip(),
    "sarima": """
Seasonal ARIMA extends the Box–Jenkins ARIMA construction to dependence and integration at a known seasonal period m. Box and Jenkins (1970) formulated multiplicative seasonal models in which a nonseasonal ARIMA(p,d,q) polynomial is combined with seasonal autoregressive, differencing, and moving-average polynomials (P,D,Q)_m. The multiplication creates cross-lag structure rather than two unrelated models. For example, monthly data with m=12 can contain both recent-month dynamics and dependence at lags 12, 24, and beyond. The seasonal period must come from the observation frequency or domain; it is not synonymous with forecast horizon.

Seasonal differencing addresses a seasonal unit root, not every visually seasonal pattern. Hylleberg et al. (1990) developed formal testing for unit roots at seasonal frequencies. Osborn et al. (1988) developed the seasonal-integration regression behind the OCSB decision, while Canova and Hansen (1995) constructed tests with stable seasonality as the null. These tests have different hypotheses and therefore may disagree. Chrono Stream offers OCSB, Canova–Hansen, a seasonal-lag ACF rule, or manual D. In the automatic path, seasonal differencing is considered before regular differencing; this ordering reduces the risk that regular differencing is used to absorb a seasonal unit root. The ACF rule is explicitly labeled a heuristic because its fixed 0.30 floor and approximate sampling band do not constitute a formal seasonal-unit-root test.

The remaining workflow inherits the ARIMA literature. Box–Cox or Yeo–Johnson transformation is fitted before mean-stationarity decisions (Box & Cox, 1964; Yeo & Johnson, 2000). Regular d can be assessed with ADF, KPSS, Phillips–Perron, or a consensus of opposing nulls (Dickey & Fuller, 1979; Kwiatkowski et al., 1992; Phillips & Perron, 1988). Seasonal and nonseasonal ACF/PACF peaks guide P, Q, p, and q but do not determine a unique model. Candidate models are compared with AIC, AICc, BIC, HQIC, or rolling-origin forecast error (Akaike, 1974; Hannan & Quinn, 1979; Hurvich & Tsai, 1989; Schwarz, 1978), after any mandatory diagnostic requirements have been applied.

Diagnostic checking is particularly important because SARIMA can become heavily parameterized. Chrono Stream evaluates convergence, all nonvariance coefficient p-values, AR and MA polynomial roots, standardized-residual mean, one selected normality test, degrees-of-freedom-corrected Ljung–Box or Box–Pierce statistics at multiple lags, and optional ARCH effects (Anderson & Darling, 1952; Box & Pierce, 1970; Engle, 1982; Jarque & Bera, 1980; Lilliefors, 1967; Ljung & Box, 1978; Shapiro & Wilk, 1965; Student, 1908). Seasonal white-noise lags include m and 2m when feasible. Requiring every individual coefficient to be significant and residuals to pass normality is stricter than many forecast-oriented applications, so policy controls allow those gates to be mandatory, advisory, or disabled while keeping the outcome visible.

SARIMA is effective for one dominant, stable seasonal cycle in a sufficiently long, regularly spaced series. It needs enough observations to identify seasonal coefficients and to leave useful degrees of freedom after differencing. It is less suitable for multiple or changing seasonalities, complex holiday effects, abrupt interventions, and large periods relative to sample length. Seasonal over-differencing can induce unnecessary moving-average structure, while an excessive (p,q,P,Q) grid can produce fragile fits. Accordingly, a defensible report should give the transformation, d and D evidence, selected order, search space, selection criterion, parameter and root diagnostics, residual tests with their lags and alpha, and genuine out-of-sample accuracy—not just the final SARIMA label.
""".strip(),
    "stl": """
Seasonal adjustment by Census Method II culminated in X-11, documented by Shiskin et al. (1967). X-11 uses iterative moving-average filters, treatment of extreme observations, trading-day options, and a substantial diagnostic framework to estimate trend-cycle, seasonal, and irregular components. Cleveland and Tiao (1976) later provided a stochastic interpretation of Census Method II filters, clarifying that moving-average seasonal adjustment can be understood in relation to underlying component models. These publications define official X-11 and prevent a common historical error: any decomposition followed by forecasting is not automatically an X-11 implementation.

STL—seasonal-trend decomposition using loess—was introduced by Cleveland et al. (1990) as a different and flexible procedure. STL iteratively applies locally weighted regression smoothers to estimate a trend and a periodically indexed seasonal component, with an optional robust loop that downweights large residuals. It accommodates arbitrary integer seasonal periods and allows the smoothness of trend and seasonality to be controlled. Unlike the full Census X-11 system, STL by itself is a decomposition algorithm, not a complete forecasting model; forecasts require explicit rules for extending components beyond the observed sample.

Chrono Stream calls this feature “STL Decomposition Forecast (X-11-inspired).” It executes robust STL, extrapolates the estimated trend by a local linear fit, and cycles the historical mean STL seasonal estimate for each phase. The X-11 inspiration is historical and conceptual—decompose a series into systematic and irregular parts—not software equivalence. This approach is a useful transparent benchmark for stable seasonality and a locally smooth trend. It can fail when the seasonal pattern evolves, multiple seasonal cycles coexist, the endpoint trend is unstable, or future shocks dominate. Its optional band is a normal-reference summary based on in-sample residual standard deviation, not an empirical-quantile interval or official X-11/X-13 output. A scholarly description should therefore cite Shiskin et al. and Cleveland and Tiao for the X-11 lineage, cite Cleveland et al. for the algorithm actually run, and explain the distinction directly.
""".strip(),
    "mstl_ets": """
Bandara, Hyndman, and Bergmeir (2025) introduced Multiple Seasonal-Trend decomposition using Loess (MSTL) for series containing more than one seasonal pattern. MSTL builds on the STL procedure of Cleveland et al. (1990), repeatedly estimating seasonal components for specified periods and refining them through iterations. This is useful for structures such as hourly observations with daily and weekly cycles, where a one-period decomposition cannot represent both repetitions. The periods are inputs to the procedure rather than facts discovered without analyst judgment, and each must be sampled often enough to distinguish a recurring pattern from trend or noise. Robust STL fitting can reduce the influence of large remainder observations, but robustness does not guarantee that an unusual event will not affect endpoint components.

MSTL is a decomposition algorithm, not a complete forecasting rule. It estimates trend, several seasonal components, and a remainder over the observed sample, but the paper does not force one particular model for their future values. A forecast implementation must therefore state how every component is extended. Chrono Stream subtracts the sum of the MSTL seasonal components and fits a nonseasonal additive-error ETS model to that adjusted series. The ETS candidates are level only, additive trend, and damped additive trend, selected among converged fits using AICc, AIC, or BIC unless a user fixes the structure. This downstream state-space step is grounded in the ETS framework of Hyndman et al. (2002), but the particular MSTL-plus-ETS combination and candidate boundary are explicit application choices rather than claims about the defining MSTL publication.

For every seasonal period, Chrono Stream takes the final complete decomposed cycle, repeats it through the requested horizon, and adds all repeated seasonal paths to the adjusted ETS forecast. This makes the result reproducible and interpretable: a user can inspect the exact terminal cycle applied for each period. It also creates a strong stability assumption. Seasonal shape and amplitude cannot evolve after the endpoint, interactions among seasons are only those already reflected in the additive decomposition, and a wrong period can create plausible-looking artifacts. The displayed interval shifts the ETS state-space interval by the fixed repeated seasonal path; it includes uncertainty for the adjusted ETS component but not decomposition, period choice, or future seasonal evolution. MSTL + ETS is therefore most defensible when multiple additive cycles are credible and well observed, with periods justified from the sampling process and performance compared chronologically against seasonal-naive, one-season ETS, TBATS, and simpler baselines.
""".strip(),
    "prophet": """
Prophet was introduced by Taylor and Letham (2018) as a practical forecasting system for business time series with strong calendar structure, missing observations, outliers, and trend changes. Its core is a decomposable model in which the observation is represented by a trend, seasonal functions, holiday or event effects, and an error term. The architecture prioritizes analyst-adjustable components and scalable fitting over automated selection from a single classical model family. Taylor and Letham explicitly described both a piecewise linear trend and a saturating logistic trend, automatic changepoint regularization, Fourier seasonal bases, and holiday regressors.

The piecewise trend is related to structural time-series reasoning: Harvey and Shephard (1993) developed structural formulations in which trend and seasonal components have explicit probabilistic roles. Prophet is not identical to those state-space models, but that literature provides an important conceptual foundation for decomposing a series into interpretable latent components. Prophet represents periodic seasonality through partial Fourier sums and uses priors to regularize flexibility. Changepoints permit the growth rate to change, while the prior scale controls whether the fitted trend is smooth or highly adaptive.

Prophet is most useful when timestamps carry meaningful calendar information, history spans the seasonal cycles of interest, and trend changes are more plausible than short-lag autoregressive dynamics. It does not automatically make arbitrary data “forecastable,” and it can extrapolate poorly after unprecedented regime changes. Flexible trend and seasonal components may fit anomalies, while default annual or weekly seasonalities may be inappropriate for the sampling frequency. Chrono Stream uses the Prophet package directly, supplies the dated target series, controls built-in seasonalities based on the data configuration, and returns Prophet uncertainty intervals. Those intervals depend on the package's assumptions about future trend changes and observation noise. A sound analysis should document frequency, enabled seasonalities, changepoint settings, any holiday regressors, and held-out accuracy rather than relying on Prophet's convenience as evidence of validity.
""".strip(),
    "lstm": """
Long short-term memory (LSTM) networks were introduced by Hochreiter and Schmidhuber (1997) to address vanishing or exploding error flow in recurrent neural networks. The memory cell and multiplicative gates created paths along which information and gradients could persist across long delays. Gers et al. (2000) added the forget gate, allowing a cell to reset state that is no longer useful, and Gers et al. (2001) evaluated LSTM in time-series prediction settings. These papers establish LSTM as a recurrent sequence-learning architecture; they do not imply that an LSTM is universally superior to statistical or fixed-window baselines.

An LSTM processes an ordered sequence through a hidden state and cell state. Input, output, and forget gates regulate which new information is written, which stored information is retained, and which state is exposed. For univariate forecasting, a common supervised construction converts the series into overlapping lookback windows and next-value targets. Scaling is usually necessary for stable optimization. A multi-step forecast may be direct, multi-output, sequence-to-sequence, or recursive. Recursive forecasting is simple but creates a distribution shift because predicted values, rather than observed values, become later inputs.

Chrono Stream implements a compact single-layer LSTM trained on normalized univariate rolling windows and recursively feeds back one-step predictions. This makes the architecture accessible and reproducible, but it deliberately omits exogenous variables, probabilistic output, ensembles, and elaborate tuning. LSTM performance is sensitive to lookback, hidden units, initialization, optimizer, epochs, scaling, and sample size. Overlapping windows do not create independent information, so a series that looks “large” after windowing may still contain little historical variation. Neural models also do not remove the need for time-ordered validation; random train–test shuffling would leak future structure. A defensible literature review should therefore present LSTM as a flexible nonlinear learner, explain the gating innovation, state the app's recursive strategy, and compare it against simpler benchmarks on a temporally held-out period.
""".strip(),
    "cnn": """
Convolutional neural networks developed from architectures that exploited local receptive fields and shared feature detectors. Fukushima's neocognitron (1980) provided an influential hierarchical, shift-tolerant precursor. LeCun et al. (1989) trained shared convolutional weights end to end with backpropagation, and LeCun et al. (1998) consolidated the gradient-based convolutional architecture. Although these works focused on spatial patterns, the same operation can slide along time. Borovykh et al. (2017) explicitly developed convolutional architectures for time-series forecasting, demonstrating how causal and dilated filters can learn temporal features.

In a one-dimensional forecasting CNN, kernels convolve over a lag window and learn local motifs such as slopes, pulses, or short cycles. Weight sharing makes the same motif detectable at different positions and typically uses fewer parameters than a fully connected network over the same window. Pooling or dilation can expand the receptive field, after which dense layers map extracted features to forecasts. A plain finite-window CNN has no persistent state beyond its receptive field; long dependencies must fit inside the window or be reached through depth and dilation.

Chrono Stream uses a compact one-dimensional CNN on normalized univariate rolling windows and makes recursive multi-step forecasts. It is intentionally much smaller than the deep dilated architecture studied by Borovykh et al. (2017), so that citation establishes the temporal-convolution approach rather than an exact architectural reproduction. CNNs can model nonlinear local interactions, but results are sensitive to kernel size, lookback, filters, training seed, epochs, and sample size. Recursive feedback compounds error, and a high-capacity network can memorize overlapping training windows. Consequently, the method should be assessed with chronological validation, repeated fits when stochastic variability matters, and direct comparison with moving-average, exponential-smoothing, and ARIMA baselines.
""".strip(),
    "nbeats": """
Oreshkin, Carpov, Chapados, and Bengio (2020) introduced N-BEATS as a deep forecasting architecture formed from fully connected basis-expansion blocks. A block maps an input history to two vectors: a backcast intended to explain part of that history and a forecast contribution for the future horizon. The backcast is subtracted before the next block, while forecast contributions are added. These backward and forward residual links allow successive blocks to explain remaining structure and assemble a direct multi-step prediction. The defining paper described both a generic architecture with learned backcast and forecast heads and interpretable stacks whose outputs are constrained to polynomial trend and harmonic seasonal bases. Those are related but materially different configurations.

N-BEATS converts forecasting into supervised learning over complete backcast–forecast pairs. The lookback and requested horizon jointly determine how many training examples exist: increasing either removes usable rows, and overlapping windows do not create independent historical regimes. Direct multi-output training avoids feeding early predictions back into later horizon inputs, but it asks one network to learn the complete horizon-specific response and changes the training problem whenever the requested horizon changes. The original paper also evaluated large collections of series, ensembles, and extensive configurations. Strong results from that setting cannot be transferred automatically to a small local univariate network, and the generic learned bases should not be described as inherently interpretable merely because the architecture has backcast and forecast heads.

Chrono Stream implements a compact generic N-BEATS. It fits a StandardScaler only on the current training partition, constructs past-only complete windows, uses repeated dense ReLU layers to generate learned backcast and forecast vectors, trains with Adam and mean-squared error without shuffling, and uses seed 42. It produces the entire requested horizon directly. It does not implement the paper's constrained trend/seasonality basis stacks, global cross-series training, or forecast ensemble. Historical fitted values use the first output of each complete training window, and the displayed uncertainty band is a residual approximation rather than a learned predictive distribution. N-BEATS is best treated as a data- and compute-intensive nonlinear comparator. A defensible assessment states the exact architecture and horizon, confines scaling and fitting to each chronological partition, checks whether enough genuinely distinct history exists, and compares the untouched holdout with naive and classical forecasts.
""".strip(),
    "tcn": """
Bai, Kolter, and Koltun (2018) evaluated a generic Temporal Convolutional Network as an alternative to recurrent architectures for sequence modeling. Their TCN combines causal one-dimensional convolutions, exponentially increasing dilation, residual connections, and equal-length input and output sequences. Causality means an output at one position cannot depend on later positions. Dilation spaces kernel taps apart so stacked layers can reach far into history without using a recurrent hidden state, while residual shortcuts make deep optimization easier. WaveNet by van den Oord et al. (2016) is an important causal dilated-convolution predecessor, but it is a probabilistic generative model for raw audio; citing that lineage does not make every TCN an implementation of WaveNet.

The reachable history is governed by the kernel width, dilation schedule, number of convolutions in each residual block, and supplied lookback. A nominal receptive field longer than the input window receives left-side causal padding rather than additional observations. A forecasting TCN can predict an entire future vector, separate horizons, or one next value recursively; this choice is not determined by convolution alone. Recursive use trains on observed windows and later forecasts on windows increasingly containing its own output, so error and distribution shift can accumulate. Dropout, filter count, depth, scaling, optimization, seed, and sample size all affect results, and adjacent overlapping windows remain highly dependent examples.

Chrono Stream builds a compact Bai-inspired residual network with two causal Conv1D layers per block, dilations 1, 2, 4, and onward, optional spatial dropout, a one-by-one shortcut when channel dimensions differ, and a dense scalar head applied to the final causal state. Standardization is fitted only to the active training partition, rows remain in temporal order, and seed 42 improves repeatability. The one-step output is inverse-scaled and fed back recursively for multiple horizons. This is not the complete benchmark architecture or experimental protocol of Bai et al. (2018), and it is not WaveNet's gated probabilistic audio system. Its interval is derived from historical residual dispersion, not a calibrated neural predictive law. TCN should be compared with the app's plain CNN, LSTM, and simple statistical baselines under the same chronological holdout, with the effective receptive field and padding disclosed rather than treating dilation as free long-memory evidence.
""".strip(),
    "xgboost": """
Gradient boosting constructs a strong predictor by adding weak learners sequentially in the direction that reduces a differentiable loss. Friedman (2001) formulated gradient boosting as function-space optimization, establishing the general statistical learning framework. Chen and Guestrin (2016) introduced XGBoost, combining regularized tree boosting with shrinkage, column and row subsampling, sparsity-aware split finding, and efficient systems design. Time-series forecasting is not a native operation of a decision tree, so an ordered series must first be represented as supervised features such as lags and calendar or exogenous variables.

For a univariate lag model, the feature vector at time t contains y_(t-1),...,y_(t-L), and the target is y_t. Boosted trees partition this lag space and sum piecewise-constant contributions, allowing thresholds and interactions that linear autoregression cannot express. Multi-step strategy is a separate design choice. Ben Taieb et al. (2012) compared recursive and direct approaches and showed that the strategy affects bias, variance, and error propagation. Recursive forecasting estimates one next-step model and feeds each prediction back; direct forecasting trains horizon-specific models; multi-output approaches estimate several horizons jointly.

Chrono Stream trains XGBoost on lagged univariate windows and uses recursive forecasts. It exposes major regularization and tree controls but does not add calendar features or external regressors automatically. The method can capture nonlinear lag interactions and is often strong on medium-sized structured data, yet it cannot extrapolate a smooth numerical trend in the same way as a trend model because trees predict combinations of learned terminal values. Long lookbacks reduce the number of usable training rows, recursive forecasts can settle into fixed patterns, and random splitting would leak temporal information. A responsible report should specify the lag construction, boosting parameters, recursive strategy, chronological validation design, and comparison benchmarks. Friedman (2001) supports the boosting principle, Chen and Guestrin (2016) supports the actual learner, and Ben Taieb et al. (2012) supports explicit treatment of the multi-step strategy.
""".strip(),
    "lagged_linear": """
Lagged linear regression sits at the intersection of autoregression and supervised least squares. Yule (1927) provided a foundational autoregressive construction in which present values depend linearly on their own lagged history, while the least-squares principle itself predates modern time-series analysis and was first published by Legendre (1805). A lag regression of y_t on y_(t-1), ..., y_(t-p) resembles an autoregression in its conditional-mean equation, but terminology matters: fitting a generic regression learner to constructed rows does not automatically supply the complete stochastic assumptions, innovation likelihood, stationarity restrictions, or exact forecast distribution associated with a formally specified AR model.

The essential forecasting design is causal row construction. Every lag must be shifted, every rolling mean or standard deviation must end at t-1, and a seasonal lag must refer to an earlier observed phase. Calendar values for the target timestamp are admissible because they are known in advance; centered smoothers or contemporaneous target-derived summaries are not. Lag-count selection must also respect order. Tashman (2000) explains why forecast-origin evaluation and coefficient recalibration choices determine whether an out-of-sample comparison is meaningful. Expanding folds imitate repeated historical origins without training on later targets. When a one-step equation is used for several horizons, forecasts are recursive: an early predicted value becomes an input. Ben Taieb et al. (2012) shows why this strategy is distinct from direct or multi-output alternatives and why propagation can dominate long-horizon performance.

Chrono Stream implements ordinary least squares on past-only lag, optional trailing-summary, longer seasonal-lag, and known-calendar features. Automatic mode searches a bounded lag range with expanding-window RMSE wholly inside the current fit partition; the untouched outer holdout remains the final comparison. The full pipeline is then fitted independently on all available observations for the future run. Coefficients are useful for describing the fitted linear equation, but correlated adjacent lags can make them unstable and ordinary iid significance claims would be inappropriate without a time-series covariance analysis. The residual-based bands shown by the app are deliberately labeled approximate because OLS on recursive lag rows does not itself deliver the calibrated multi-horizon distribution being displayed. This method is therefore best used as a transparent linear benchmark, evaluated chronologically and compared with naive, seasonal-naive, smoothing, and formally stochastic alternatives.
""".strip(),
    "regularized_regression": """
Regularized lag regression responds to a structural feature of time-series design matrices: neighboring lags and overlapping rolling summaries are usually strongly correlated. Hoerl and Kennard (1970) introduced ridge regression to stabilize nonorthogonal least-squares problems by adding an L2 penalty. Tibshirani (1996) introduced the Lasso, whose L1 constraint can shrink some coefficients exactly to zero and thereby combine estimation with variable selection. Zou and Hastie (2005) developed Elastic Net to combine L1 and L2 behavior, emphasizing its grouping advantage when predictors are strongly correlated. These papers define different estimators, so Chrono Stream presents them as selectable penalty variants under one shared lag-regression contract rather than falsely treating them as identical algorithms.

Penalty strength governs a bias–variance tradeoff rather than a hypothesis test. Ridge generally retains every lag but reduces unstable magnitude; Lasso may choose one representative among correlated lags; Elastic Net can retain correlated groups while remaining sparse. Since a penalty acts on coefficient scale, predictors must be standardized consistently. Fitting one scaler before validation would leak the distribution of later folds, so scaling and regression belong in one pipeline that is refitted inside every expanding origin. Alpha and, for Elastic Net, the L1 ratio are tuning parameters whose apparent optimum depends on origins, horizon, loss, and candidate grid. Tashman's (2000) analysis supports ordered pseudo-out-of-sample evaluation, but a winning CV value still has selection variability and is not evidence that excluded coefficients are truly zero.

Chrono Stream constructs the same causal feature family used by its other lag regressors and places StandardScaler plus Ridge, Lasso, or Elastic Net in a single sklearn pipeline. Automatic mode uses a bounded alpha grid and a small set of Elastic Net mixtures; manual mode accepts the user's exact settings. The scaler and estimator are learned only on each fold's earlier rows, then refitted on the complete current partition. Multi-step forecasts are recursive, so shrinkage can stabilize the one-step map without removing distribution shift at later horizons. Reported standardized coefficients describe the fitted pipeline but are not accompanied by ordinary significance claims. The approximate residual interval also omits uncertainty from tuning, coefficient selection, and recursive feedback. Appropriate use therefore requires chronological holdout evidence, coefficient-stability caution, and comparison against unregularized OLS and simpler temporal baselines.
""".strip(),
    "cart": """
Classification and Regression Trees were systematized by Breiman, Friedman, Olshen, and Stone (1984). For a continuous response, CART uses binary recursive partitioning to choose feature thresholds that reduce within-node squared error, then predicts a constant such as the mean response in each terminal region. The same framework covers classification with a different impurity objective, but a forecasting page with a continuous target is specifically regression CART. “Decision tree” is therefore an accessible label for the same methodology, not grounds for a duplicate model page. A raw ordered series is not itself a conventional tree feature matrix; lagged and other known-time predictors must first encode the state at each target.

A tree can express thresholds, interactions, and regime-like partitions that a global linear lag equation misses. Its flexibility is also its weakness: deep trees and small leaves adapt strongly to idiosyncratic rows and can change substantially after a modest data perturbation. Depth and minimum leaf size control this bias–variance tradeoff. Time-ordered tuning is indispensable because shuffled folds allow later regimes to influence earlier validation. Expanding forecast origins follow the out-of-sample principles discussed by Tashman (2000). For multiple horizons, a recursively reused one-step tree faces a further problem: its predictions are terminal-node averages, so forecast-generated lag states can settle into constant regions and early errors can redirect all subsequent branch choices.

Chrono Stream fits one seeded sklearn DecisionTreeRegressor to causal lag, trailing-summary, seasonal-lag, and optional known-calendar features. Automatic mode searches a deliberately small depth/leaf grid inside expanding folds; manual mode fixes both controls. The final record exposes actual depth, number of leaves, feature names, impurity importances, and every candidate score. Impurity importance is a descriptive allocation of split reduction, not a hypothesis test or proof of causal relevance. Regression trees generally do not extrapolate a numerical trend beyond response regions represented in training, so drift and linear benchmarks remain especially important. The displayed bands are residual approximations rather than native CART confidence intervals, and recursive horizon error is not calibrated by fitting more leaves. The method is most defensible when nonlinear thresholds are plausible, data contain enough repeated regimes, and held-out forecasts justify the added flexibility.
""".strip(),
    "random_forest": """
Random Forests were defined by Breiman (2001) as collections of tree predictors driven by independent randomized inputs. In the familiar regression implementation, trees grow from bootstrap samples and consider random subsets of predictors at splits; their outputs are averaged. The method inherits recursive-partitioning structure from CART (Breiman et al., 1984) while using diversity to reduce the variance of one unstable tree. Feature subsampling is not cosmetic: reducing correlation among reasonably strong trees is central to why averaging can improve generalization. Applying the forest to forecasting still requires an explicit transformation from ordered observations to supervised lag rows.

Tree count primarily controls Monte Carlo stability once other settings are fixed, whereas depth, minimum leaf size, and feature fraction govern complexity and diversity. Bootstrap rows drawn from overlapping lag windows should not be confused with independent time-series observations, and ordinary out-of-bag summaries do not replace a chronological evaluation of future regimes. Tashman (2000) supports rolling or expanding origins for forecast comparison. A one-step forest used recursively averages historical leaf targets at every horizon; it can model nonlinear lag interactions but does not naturally project a response beyond learned target regions. Forecast feedback can also create lag vectors unlike those seen with observed histories, compounding the usual recursive-strategy problem.

Chrono Stream uses sklearn RandomForestRegressor with bootstrap sampling, a fixed seed, one worker, and past-only lag features. Automatic tuning bounds cost by fixing 100 trees while comparing a small depth, leaf-size, and feature-fraction grid in expanding folds. Manual mode also exposes tree count. The model record contains all candidate scores, the selected structure, bootstrap status, feature importances, and recursion disclosure. Fixed seeds improve reproducibility but do not turn correlated lag windows into independent evidence. Impurity importance can favor variables with more effective split opportunities and should not be read as statistical significance. Likewise, the app's residual bands are explicitly approximate and are not quantile-regression-forest, bootstrap, or conformal intervals. Random Forest is consequently a useful nonlinear comparator when enough historical states exist, but it should earn preference through the outer holdout against CART, seasonal persistence, drift, smoothing, and statistical models.
""".strip(),
    "support_vector_regression": """
Support Vector Regression extends support-vector learning from separating classes to estimating real-valued functions. Vapnik (1995) established the support-vector function-estimation framework, and Vapnik, Golowich, and Smola (1997) presented the method for regression estimation. Drucker et al. (1997) provided an early application and comparison with tree ensembles and ridge regression, while Smola and Schölkopf (2004) later gave a detailed tutorial on the epsilon-insensitive objective, regularization, kernels, sparsity, and computation. SVR estimates a function that is deliberately insensitive to errors within an epsilon tube and penalizes violations outside it. The constant C trades function flatness or margin regularity against violation cost, while kernels replace explicit high-dimensional feature expansion with similarity calculations.

For lag forecasting, a linear kernel gives a regularized global relation among past values; a radial-basis kernel gives a smooth local nonlinear surface over standardized lag states. Scaling is essential because both Euclidean kernel distance and the penalty geometry depend on feature magnitude. Scaling the target also makes epsilon and C interpretable relative to target dispersion rather than raw units. Epsilon controls how many rows become active support vectors, C controls tolerance for deviations, and gamma controls RBF locality. These interacting parameters make shuffled generic cross-validation particularly inappropriate for an ordered series. Expanding origins keep validation targets later than training targets, consistent with Tashman's (2000) forecast-evaluation design. They estimate predictive error for the selected origins but do not supply an inferential null distribution or prove stability after a break.

Chrono Stream fits separate feature and target StandardScalers inside a transformed-target sklearn pipeline, so every validation fold learns both scales only from its own past and predictions return to original units. Automatic mode compares bounded linear and RBF configurations across C, epsilon, and RBF gamma; manual mode fixes the main settings on the standardized target scale. Selected values, candidate errors, support-vector count, scaler metadata, and causal feature definitions are retained. Multiple horizons are recursive, which means the nonlinear surface is queried with prior predictions and can be evaluated outside the distribution of observed lag states. SVR offers no native predictive distribution here; a descriptive residual band is not a calibrated support-vector interval and is unavailable when in-sample residual variance is degenerate. It is a reasonable moderate-sample nonlinear learner when smooth lag relations are plausible, but tuning sensitivity, computational growth, opaque kernels, weak trend extrapolation, and recursive distribution shift make chronological comparison with simpler models mandatory.
""".strip(),
    "knn_regression": """
k-nearest-neighbor regression is a local nonparametric estimator rather than a fitted global equation. Stone (1977) established consistency conditions for broad probability-weight estimators and constructed nearest-neighbor rules within that framework. Altman (1992) explained kernel and nearest-neighbor regression as local versions of familiar location estimates. A time-series adaptation embeds each historical target in a vector of values known immediately before it, then searches for past states resembling the current state. The forecast is an average of successors attached to the closest states. This intuition is compelling when patterns recur, but the theoretical iid consistency setting cannot simply be transferred as a finite-sample guarantee for dependent, changing data.

Neighbor count is a smoothing parameter: k=1 has low local bias and high variance, while larger k pools less similar regimes. Uniform weighting treats all selected states equally; inverse-distance weighting emphasizes closer analogs. Manhattan and Euclidean metrics produce different neighborhoods, and unscaled features with larger variance can dominate either distance. High-dimensional lag construction creates a curse of dimensionality in which all states may appear similarly distant. Temporal validation must therefore tune the complete scale–distance–k pipeline in order. The smallest training fold also limits legal k values, and later observations cannot be used to determine scaling or neighbors for earlier validation targets.

Chrono Stream standardizes its causal lag, trailing-summary, seasonal-lag, and known-calendar features inside each sklearn pipeline. Automatic mode bounds neighbor candidates by the first expanding fold and searches k, weighting, and Manhattan/Euclidean power; manual mode fixes them. Every future forecast is appended before the next neighborhood is queried. This recursive update can move the state into areas with weak historical analogs and, because kNN predicts averages of observed targets, it does not naturally extrapolate an unseen trend or level. The reported interval is a residual approximation, not a formal nearest-neighbor conditional quantile band. kNN is most useful as an interpretable analog benchmark when regimes repeat and feature dimension remains modest, with its value established by a chronological outer holdout rather than by training proximity.
""".strip(),
    "extra_trees": """
Extremely Randomized Trees were introduced by Geurts, Ernst, and Wehenkel (2006) as a tree ensemble that strongly randomizes both candidate attributes and cut points. This distinguishes Extra Trees from Breiman's (2001) Random Forest formulation, which is commonly associated with bootstrap samples and random feature subsets but chooses split thresholds by optimizing over observed candidates. In the Extra Trees extreme, stronger split randomization can reduce tree correlation and computation, although it may increase bias. Both methods average piecewise-constant regression trees and both require an explicit lag-feature representation before they can forecast an ordered series.

The ensemble's behavior depends on tree count, maximum depth, leaf size, feature fraction, and whether bootstrap sampling is used. More trees stabilize the random average but do not repair a biased feature contract or absent future regime. Random thresholds can help decorrelate trees when lag predictors are redundant, yet the output still lies within averages of target regions learned by terminal leaves. Chronological tuning is necessary because random train/test folds leak regime information across time. Expanding origins modeled on the forecast-evaluation principles reviewed by Tashman (2000) preserve order and make failures visible. Recursive multi-step use remains a separate strategy whose inputs increasingly contain model output rather than observations.

Chrono Stream fits sklearn ExtraTreesRegressor without bootstrap, with a fixed seed and one worker. Automatic mode uses 100 trees while tuning a bounded depth, leaf-size, and feature-fraction grid on expanding folds; manual mode exposes those settings and tree count. The audit record explicitly states split-threshold randomization, bootstrap status, feature importances, candidate errors, and recursive behavior. Feature importance is descriptive, and the residual approximation shown around forecasts is not an ensemble-confidence, quantile, bootstrap, or conformal guarantee. Extra Trees should be treated as a fast, highly randomized nonlinear comparator rather than a universal improvement over Random Forest: whether reduced variance offsets additional bias is series-specific and must be judged on the untouched outer holdout against simpler extrapolative and seasonal benchmarks.
""".strip(),
    "theta": """
Assimakopoulos and Nikolopoulos (2000) introduced the Theta model as a decomposition of a time series into “Theta lines” whose second differences, and therefore curvature, are modified while mean and slope are preserved. Their practical M3 implementation combined a theta-zero line representing long-term direction with a theta-two line emphasizing local curvature, then extrapolated and recombined them. The method's strong competition performance made it an important benchmark. Hyndman and Billah (2003) subsequently simplified the algebra and showed that the conventional forecast can be represented through simple exponential smoothing with drift, clarifying that the operational method is much less mysterious than its original decomposition language suggests.

In the common theta=2 case, the forecast combines a long-run regression slope contribution with an SES level. Fiorucci et al. (2016) generalized this construction by optimizing the short-term theta line, providing the relevant lineage when theta is not fixed at two. The original procedure seasonally adjusts eligible data before the nonseasonal forecast and restores the seasonal component afterward. Seasonality therefore requires a known period and enough repeated cycles, while multiplicative decomposition requires positive values. Parameters can be obtained through two-step OLS plus SES or through the equivalent ARIMA(0,1,1)-with-drift likelihood representation. Prediction intervals require additional innovation assumptions; they are not implied solely by the historical M3 point-forecast ranking.

Chrono Stream uses statsmodels ThetaModel and exposes automatic seasonality testing, forced adjustment, or no adjustment; automatic, additive, or multiplicative decomposition; the theta coefficient; and two-step or maximum-likelihood estimation. It produces historical fitted values as expanding-prefix one-step forecasts wherever a prefix has enough history; exactly two seasonal cycles leave none available. Its integrated-moving-average Gaussian intervals use innovation variance estimated from the same deseasonalized series used by the Theta fit, avoiding a raw-seasonal-series variance refit in the default two-step path. Theta is attractive as a parsimonious level-and-drift benchmark, not as proof that every series decomposes into stable long- and short-term information. Period mistakes, short samples, structural breaks, changing seasonal amplitude, and long-horizon drift remain material risks, so its M3 heritage should motivate comparison rather than confer automatic superiority.
""".strip(),
    "automatic_ets": """
Hyndman, Koehler, Snyder, and Grose (2002) placed exponential smoothing within an innovation state-space taxonomy indexed by Error, Trend, and Seasonality. This ETS framework connected familiar smoothing recursions with likelihood calculation, information criteria, simulation, and predictive intervals, enabling systematic automatic forecasting rather than choosing a Holt–Winters label informally. Hyndman, Koehler, Ord, and Snyder (2008) developed the state-space approach comprehensively. The taxonomy distinguishes additive and multiplicative observation errors from additive or multiplicative states; point forecasts can coincide for some structures even though their likelihoods and forecast distributions differ.

An ETS candidate may have no, additive, or multiplicative trend; a trend may be damped; and seasonality may be absent, additive, or multiplicative. Multiplicative components require a positive scale, while seasonal initialization needs repeated cycles. Maximum likelihood estimates initial states and smoothing parameters jointly. AIC, corrected AIC, and BIC trade fit against estimated complexity, but they are relative criteria without null hypotheses or universal adequacy thresholds. Automatic selection is defensible only among comparable candidates fitted to the same data and likelihood convention, and optimizer convergence must be checked separately. A selected model can still leave autocorrelation, fail after a break, or lose to a simple benchmark out of sample.

Chrono Stream fits statsmodels ETSModel across a bounded, explicit candidate grid. Nonpositive data exclude multiplicative structures, and fewer than two cycles exclude seasonal candidates. Each attempted structure retains its AICc, AIC, BIC, convergence flag, fitting error, selection eligibility, and a specific exclusion reason; a summary warning appears when at least a quarter of fitted candidates have an undefined selected criterion. Only converged candidates with finite selected criteria can win. Manual mode fits the exact requested error, trend, damping, and seasonal components. Model-native state-space intervals, parameters, and the ETS tuple are saved. This page differs from the separate manual Holt and Holt–Winters pages because its defining purpose is innovation-error structure and automatic selection across a family. Information-criterion leadership remains only one line of evidence, so Chrono Stream independently reports outer-holdout accuracy and preserves candidate diagnostics for review.
""".strip(),
    "tbats": """
De Livera, Hyndman, and Snyder (2011) introduced an innovation state-space framework for complex seasonal time series, including multiple, high-frequency, non-integer, and dual-calendar patterns. The model commonly called TBATS combines Trigonometric seasonal representation, Box–Cox transformation, ARMA error correction, Trend, and Seasonal components. Trigonometric harmonics are crucial: instead of estimating one unrestricted state for every position in a very long cycle, Fourier-like pairs represent each seasonal period compactly and can evolve. The paper derives likelihood evaluation, point forecasts, and interval expressions under Gaussian innovations and addresses the computational burden of estimating such models.

The Box–Cox family of Box and Cox (1964) can stabilize variance for positive data before state evolution; a local trend can be absent, present, or damped; and ARMA terms can absorb residual serial dependence. Multiple periods can be floating point values, which is useful when a seasonal cycle is not an integer number of sampling intervals. Flexibility comes with a substantial estimation and selection cost. Periods are not discovered from nothing: the analyst supplies candidate cycles, and harmonic counts plus components are selected within that structure. Very long seasons need enough observations to distinguish repetition from trend, while calendar disruptions and structural breaks can remain inadequately modeled even with many harmonics.

Chrono Stream lazily calls the pinned Python tbats implementation, accepts one or more comma-separated numeric periods, and requires at least two repetitions of the longest period. Automatic mode permits AIC selection over Box–Cox when values are positive, trend, and damping, with optional ARMA errors; manual mode fixes those switches. One worker avoids uncontrolled multiprocessing, and a narrowly scoped compatibility wrapper maps the package's retired sklearn validation keyword to its current spelling without changing the model. Selected periods, harmonics, lambda, damping, ARMA orders, AIC, package warnings, summary, and native Gaussian intervals are retained. TBATS is appropriate when complex seasonality is real and well sampled, but its computational sophistication is not a substitute for period justification, holdout comparison, residual review, or simpler seasonal benchmarks.
""".strip(),
    "croston_family": """
Croston (1972) addressed intermittent demand by separating positive transaction sizes from the intervals between them. Conventional exponential smoothing applied directly to a series dominated by zeros can update toward zero after every empty period and does not distinguish changing occurrence frequency from changing nonzero magnitude. Croston's construction updates exponentially smoothed demand size and inter-demand interval when a positive demand occurs, then uses their ratio as expected demand per period. Syntetos and Boylan (2005) showed that the conventional ratio is biased and developed the approximation commonly called SBA, which multiplies the Croston estimate by 1-alpha/2. The correction is tied to the smoothing formulation; it is not a generic percentage adjustment for every intermittent series.

Teunter, Syntetos, and Babai (2011) proposed TSB in an inventory-obsolescence setting. Instead of updating an interval state only when demand occurs, TSB smooths a binary occurrence indicator in every period and separately updates demand size on positive periods. Expected demand is the product of occurrence probability and positive-demand size. A sustained run of zeros therefore lowers the probability state and lets the forecast decay, unlike the constant terminal path of original Croston or SBA after their last nonzero observation. This behavior can be useful when an item becomes obsolete, but beta controls how quickly absence is interpreted as a probability change and zeros must truly mean no demand rather than missing records, unavailable stock, or censored sales.

Chrono Stream exposes original Croston, SBA, and TSB under one page with explicit nonnegative-data and exact-zero semantics. The first positive value initializes the demand-size state; its one-based position initializes the first interval and TSB occurrence probability. Manual mode accepts alpha and, for TSB, beta. Automatic mode evaluates a bounded smoothing grid with causal one-step MAE or RMSE on only the current fitting partition, retaining zero-demand periods in the loss. An all-zero partition follows a declared structural-zero rule. Every future point is the terminal expected demand per period; it is not a forecast of the next nonzero order size or its arrival date. Residual bands are clipped at zero and are only approximations, not discrete demand distributions or inventory-service guarantees. Selection by statistical error also differs from minimizing stockout, holding, or obsolescence cost, so operational use should evaluate the relevant cost function and compare against zero-aware naive benchmarks.
""".strip(),
    "linear": """
Linear trend forecasting combines the least-squares principle with time as the explanatory variable. Legendre (1805) first published the method of least squares, and Gauss (1809) supplied a probabilistic and astronomical treatment while also asserting earlier use. These works establish least-squares estimation, not a modern time-series forecast method in isolation. Fitting y_t = a + b*t turns that estimation principle into a deterministic extrapolation rule: the slope is the estimated average change per index step and future forecasts extend the same line.

The model is transparent and provides an important benchmark for whether more elaborate methods add value. Under classical independent, equal-variance, correctly specified errors, ordinary least squares has familiar optimality and inferential properties. Time-series residuals commonly violate those assumptions through serial correlation, changing variance, seasonality, and structural breaks. Yule (1926) demonstrated how trending series can exhibit misleading correlation, an enduring warning that a high in-sample R-squared or visually close line is not evidence of a stable forecasting relationship.

Chrono Stream fits observation value against integer time by least squares and extrapolates the fitted line. The index spacing is assumed regular; actual irregular timestamp gaps are not used as unequal durations. The method contains no seasonal or autoregressive component and no mechanism for a slope change after the sample endpoint. It is therefore most defensible as a descriptive baseline over horizons where a roughly constant increment is plausible. A complete analysis should inspect residual structure, sensitivity to the fitted start date, breaks, and held-out forecast error. If the linear trend wins, its simplicity is an advantage; if it loses, it still provides a meaningful reference against which the incremental complexity of other methods can be judged.
""".strip(),
    "quadratic": """
Quadratic trend forecasting is a polynomial least-squares projection rather than a separately invented stochastic time-series method. Legendre (1805) established least squares, and Gergonne (1815) developed polynomial least-squares interpolation and approximation in an explicit algebraic form. Applying those ideas to equally spaced time produces y_t = a*t^2 + b*t + c. For the fitted curve, first differences are exactly linear in the index and second differences are exactly constant, giving the curve one direction of acceleration or deceleration over its domain.

The added curvature can fit a smooth bend that a straight line misses, but polynomial extrapolation is dominated by its highest-degree term. Small changes in the estimated quadratic coefficient can therefore create large long-horizon changes, reversals, or impossible values. Refitting a complete quadratic basis is invariant to shifting the time origin, apart from numerical roundoff; apparent curvature can instead be an artifact of the training window, an outlier, seasonality, or a structural break. Yule's (1926) analysis of spurious relationships among trending series reinforces the distinction between describing the observed path and identifying a stable dynamic process.

Chrono Stream fits a degree-two polynomial to regularly spaced observation indices and evaluates it at future indices. It does not recursively update values and does not model serially dependent errors, recurring seasonality, or a saturation boundary. The method is suitable as a cautious short-horizon benchmark when domain knowledge supports smooth acceleration, but it should rarely be accepted from in-sample fit alone. Users should plot the extrapolation, test sensitivity to the training window, compare it with a linear trend, and evaluate it chronologically. The literature supports the least-squares polynomial machinery; it does not justify interpreting every estimated parabola as a persistent law of the underlying phenomenon.
""".strip(),
    "exponential": """
Exponential trend forecasting assumes multiplicative growth or decline of the form y_t = A*exp(b*t), so the expected proportional change is constant under the deterministic curve. Malthus (1798) supplied an influential early domain formulation of exponential population growth, while Legendre's (1805) least-squares principle provides the fitting foundation. The curve is linearized as log(y_t) = a + b*t + error and therefore requires strictly positive observations. This model should not be confused with exponential smoothing: exponential trend describes a functional growth shape, whereas exponential smoothing describes geometrically declining weights or evolving states.

Log-scale least squares estimates the center of log(y), and simply exponentiating a fitted log mean generally targets a conditional median on the original scale rather than its conditional mean. Duan (1983) developed the nonparametric smearing estimator to correct retransformation bias without requiring normally distributed log errors, and Miller (1984) analyzed bias in retransformed log-linear models. These contributions are essential when an app reports original-scale mean forecasts rather than only median-like back-transformations.

Chrono Stream fits a linear trend to logged positive values, estimates Duan's smearing factor from training residuals, and multiplies exponentiated predictions by that factor. This is faithful to the cited retransformation literature. The model is useful when percentage growth is approximately stable over the forecast horizon, but compounding makes long-range results extremely sensitive to the estimated slope. It has no saturation, seasonal, autoregressive, or break component; a short-lived surge can generate explosive forecasts. Smearing also assumes that the retransformation factor is sufficiently stable across the predictor range. A defensible report should distinguish mean from median forecasts, state the positivity restriction and smearing factor, inspect log-scale residuals, and validate the compounding trajectory out of sample.
""".strip(),
    "logarithmic": """
The logarithmic trend y_t = a*log(t) + b combines least-squares curve fitting with an imposed diminishing-change shape. Legendre (1805) supplies the estimation foundation. Fechner (1860) is an early defining scientific use of a logarithmic response law in psychophysics, but it is not an origin paper for time-series forecasting. Accordingly, the method should be described as a deterministic curve-projection benchmark, not attributed to a single inventor of “logarithmic forecasting.”

Equal multiplicative changes in the positive time index produce equal additive changes in the fitted response, and the instantaneous slope a/t shrinks in magnitude. The curve can therefore represent rapid early growth followed by continuing but progressively smaller gains, or the corresponding pattern of decline. Starting the index at one avoids log(0), but the fitted curve depends on that origin: shifting the historical start date changes every transformed predictor and can materially change the extrapolation.

Chrono Stream regresses the observed value on log(1),...,log(n) and evaluates the curve at future integer indices. It does not estimate a finite carrying capacity, an S-shaped transition, seasonal effects, or serial dependence. Yule (1926) showed why shared trend can make deterministic relationships look stronger than their stochastic basis warrants. The logarithmic curve is therefore most useful as an interpretable baseline when domain knowledge supports diminishing increments and the forecast horizon is modest. Users should compare alternative time origins and training windows, inspect residual autocorrelation, and validate forecasts chronologically. A close historical fit alone is not evidence that the diminishing pattern will persist.
""".strip(),
}
