"""Copy-ready literature reviews for every forecasting method.

These reviews complement the shorter audited overviews in ``method_info.py``.  They
use only the primary or method-defining works listed in each method's APA reference
list, so an exported note remains internally consistent and ready for scholarly use.
"""

from __future__ import annotations


METHOD_LITERATURE_REVIEWS: dict[str, str] = {
    "moving_average": """
Moving averages belong to the earliest formal tools for separating persistent movement from short-run fluctuation in ordered observations. Poynting (1884) compared successive averages in an economic time series, while Hooker (1901) explicitly used a nine-year moving average to distinguish longer movement from annual variation. These contributions predate modern stochastic forecasting theory; their original purpose was primarily descriptive smoothing. Macaulay (1931) later gave a systematic treatment of moving-average graduation, including the effect of span and weights on the smoothness and timing of the resulting series. The literature therefore supports a careful historical claim: no single paper invented every use now called a “moving average,” but these works document the transition from informal averaging to an explicit time-series filter.

For a trailing simple moving average of span w, the one-step forecast is the arithmetic mean of the most recent w observations. This is a finite-impulse-response low-pass filter: short oscillations tend to cancel, while persistent local level is retained. The span controls the bias–variance trade-off. A short window responds rapidly but transmits noise; a long window is smoother but reacts slowly to level changes. Centered moving averages are useful for decomposition but require future observations and therefore cannot be used directly for real-time forecasting. A trailing average is causal, although repeated multi-step forecasting requires an additional convention because future windows contain values that have not yet been observed.

As a forecasting model, the simple moving average is most defensible as a transparent local-level benchmark. It assumes that observations within the chosen window are exchangeable enough for their mean to represent the next level, gives every included observation identical influence, and discards all earlier observations abruptly. It contains no explicit trend, seasonal, intervention, or probabilistic error component. These limitations explain why moving averages remain useful for baselines and exploratory smoothing but are rarely sufficient for series with sustained trend or recurring seasonality. Chrono Stream implements a causal trailing average, searches candidate spans by one-step-ahead training RMSE when automatic selection is enabled, and recursively inserts forecasts for horizons beyond one step. That recursive convention is operationally coherent, but uncertainty can compound and the selected in-sample span should still be checked on held-out or rolling-origin data.
""".strip(),
    "weighted_moving_average": """
Weighted moving averages developed from the broader problem of graduating noisy ordered data while retaining important shape. Spencer (1904) proposed an explicit set of unequal finite weights for smoothing sickness and mortality rates, and Henderson (1916) developed adjusted-average weights designed to reproduce local polynomial movement while suppressing irregular variation. Macaulay (1931) subsequently organized simple and weighted moving-average methods and showed that weighting is a filter-design decision rather than a cosmetic variation on averaging. These sources establish the method as a family of linear filters: the phrase “weighted moving average” does not identify one universal set of weights.

Given a window of w observations and normalized weights a_1,...,a_w, the forecast is the linear combination sum(a_i y_i), where the weights sum to one. Increasing weights toward the most recent observation produces a causal recency-weighted forecast; symmetric weights instead suit retrospective smoothing but are unavailable at a live endpoint. Weight shape determines response. Linear recency weights decline at a constant step, whereas exponential weights decline geometrically inside the finite window. Unlike simple exponential smoothing, however, a finite weighted moving average drops an observation completely once it leaves the window and need not arise from a stochastic state-space model.

The approach is useful when substantive knowledge says that recent values are more informative and when interpretability matters more than a rich data-generating model. Its performance depends jointly on window length and weight profile. Too much recency emphasis follows noise; too little adapts slowly to structural change. Fixed weights do not estimate trend, seasonality, nonlinear response, or conditional variance, and recursive multi-step use substitutes predictions for observations. Chrono Stream offers linear or exponential recency patterns, normalizes the weights, and can select the window by one-step-ahead training RMSE. This implementation is a pragmatic forecast filter rather than the symmetric Spencer or Henderson graduation formula itself; those historical papers establish the weighted-filter tradition, not the app's exact modern weight presets. External validation remains important because optimizing a window on the same series can favor an overly responsive specification.
""".strip(),
    "single_exponential_smoothing": """
Single exponential smoothing (SES) emerged as a forecasting method for series whose local level changes gradually but that lack a persistent trend or seasonal cycle. Brown (1956) provided an early widely documented demand-forecasting treatment, and Holt's 1957 report, later reprinted as Holt (2004), placed exponentially weighted level updates within a broader family that could also represent trend and seasonality. Muth (1960) supplied the key statistical justification: under an appropriate local-level process, an exponentially weighted forecast has optimal properties. Thus, SES is more than an arbitrary recency rule; it can be interpreted both as a forecasting recursion and as the optimal filter for a particular stochastic model.

The level update is l_t = alpha*y_t + (1-alpha)l_(t-1), with 0 < alpha <= 1, and every future point forecast equals the final estimated level when no trend is included. Expanding the recursion shows geometrically declining weights on older observations plus an initialization term. Large alpha values adapt quickly but produce a variable level estimate; small values smooth strongly but lag after shifts. This infinite geometric memory distinguishes SES from a finite weighted moving average. Estimation ordinarily chooses alpha and the initial state by minimizing a likelihood or squared-error objective instead of treating alpha as a universal constant.

SES is appropriate for short-horizon forecasts of a noisy, nonseasonal level and provides a strong benchmark because it is parsimonious, adaptive, and interpretable. It is misspecified when trend or seasonality is systematic, and its constant point forecast should not be mistaken for an assertion that the actual series will be flat. Forecast uncertainty grows with horizon even though the point forecast does not change. Chrono Stream uses the statsmodels simple-exponential-smoothing implementation, either estimates alpha automatically or accepts a user value, and reports the fitted level recursion. The historical and optimality literature supports that implementation, while also implying a practical model-selection rule: visible trend calls for Holt's method and stable repeating seasonality calls for a seasonal extension rather than an artificially large smoothing coefficient.
""".strip(),
    "double_exponential_smoothing": """
Holt's linear trend method extends exponential smoothing from a changing level to a changing level plus slope. Holt developed the coupled recursions in a 1957 research memorandum reprinted as Holt (2004), allowing trend to be updated rather than imposed by a global regression line. Winters (1960) built on this system for seasonal sales forecasting, helping establish the level–trend–seasonal family now associated with the two authors. Gardner and McKenzie (1985) later introduced and studied a damped-trend form in which the long-horizon extrapolated slope is progressively reduced. The literature therefore distinguishes ordinary Holt, which projects a linear trend indefinitely, from damped Holt, which allows near-term trend but limits distant extrapolation.

In the additive-trend formulation, the level combines the current observation with the previous level advanced by the previous trend, while the trend smooths the change between successive levels. The h-step point forecast is l_t + h*b_t for an undamped trend. With damping parameter phi between zero and one, the accumulated future trend becomes a finite geometric sum, so forecasts eventually approach an asymptote in their increments. Smoothing parameters govern how quickly level and slope respond, and their estimates are interdependent with initialization. This local recursion differs from least-squares linear trend fitting: a global regression gives all points leverage on one fixed line, whereas Holt continually updates its terminal state.

Holt's method is suitable when a nonseasonal series displays a reasonably smooth trend whose recent direction is informative. Undamped extrapolation can become implausible at long horizons, particularly after a temporary surge, so damping is often a valuable robustness option. The method does not model a repeating seasonal pattern, abrupt interventions, or autoregressive residual structure, and a trend detected over a short sample may not persist. Chrono Stream uses the statsmodels Holt implementation, permits automatic or manual level and trend smoothing, and exposes optional damping. This matches the defining recursions and the Gardner–McKenzie extension; users should compare damped and undamped forecasts out of sample rather than interpret either trajectory as a structural law.
""".strip(),
    "triple_exponential_smoothing": """
Seasonal exponential smoothing arose from extending Holt's evolving level and trend to a recurring seasonal state. Holt's 1957 report, reprinted as Holt (2004), described exponentially weighted forecasting of trends and seasonals, and Winters (1960) presented the sales-forecasting system now commonly called Holt–Winters. Gardner and McKenzie (1985) subsequently developed damping for trend extrapolation, an extension that can also be combined with seasonal exponential smoothing. “Triple exponential smoothing” is therefore a popular label for a component model with level, trend, and seasonality; it should not be confused with applying the same smoothing operation three times.

The method updates three linked states. The level represents the deseasonalized local position, the trend represents its local slope, and seasonal indices represent recurring within-cycle effects. In an additive seasonal form, the seasonal contribution is measured in the units of the series and is added to level and trend. In a multiplicative form, it scales the level and is better suited to seasonal amplitude that grows with the series; it also requires positive, nonzero data. Forecasts advance the terminal level and trend and reuse the seasonal state from the corresponding position in the cycle. The seasonal period is substantive model information, not a parameter that can be inferred reliably from very short data.

Holt–Winters is useful when seasonality is stable enough to repeat and at least two full cycles are available for initialization and estimation. It is vulnerable to incorrect period choice, evolving or multiple seasonalities, calendar effects, outliers, and abrupt level changes. Multiplicative seasonality can be numerically and conceptually inappropriate around zero, while an undamped trend may dominate long-horizon forecasts. Chrono Stream uses statsmodels' additive or multiplicative seasonal Holt–Winters model, supports additive trend and optional damping, and requires sufficient cycles. This is faithful to the level–trend–seasonal tradition, but it is not an automatic guarantee of seasonal adequacy: residual autocorrelation and rolling-origin accuracy should be inspected, especially when the seasonal pattern changes over time.
""".strip(),
    "arima": """
Autoregressive integrated moving-average modeling combines three ideas that developed separately. Yule (1927) constructed autoregressive dependence by relating a value to its own lags, while Slutzky (1937, original work published 1927) showed that finite moving sums of random causes can generate systematic serial patterns. Box and Jenkins (1970) unified autoregression, moving-average errors, differencing, identification, estimation, diagnostic checking, and forecasting into a repeatable modeling strategy. In ARIMA(p,d,q), regular differencing of order d is intended to remove stochastic mean nonstationarity, after which p autoregressive terms and q moving-average innovation terms describe the stationary dependence. This is a stochastic model of conditional means, not merely a curve fitted against time.

Variance stabilization logically precedes mean-stationarity assessment because a changing variance can distort graphical and correlation-based identification. The Box–Cox family was developed by Box and Cox (1964) for positive data, while Yeo and Johnson (2000) provided a related power family that also permits zero and negative values. Both transformations are monotone but nonlinear, so forecasts and interval endpoints must be returned to the data scale deliberately. Chrono Stream fits the transformer only on training data, applies differencing and model estimation on the transformed scale, and uses simulation through the inverse transformation to estimate original-scale means and intervals. This matters because a simple inverse of a transformed conditional mean generally is not the original-scale conditional mean.

Determining d is an inferential decision rather than a mechanical requirement to difference until a plot looks smooth. Dickey and Fuller (1979) established unit-root testing, Phillips and Perron (1988) developed a nonparametric correction for weakly dependent and heteroskedastic disturbances, and Kwiatkowski et al. (1992) reversed the hypotheses by taking stationarity as the null. The opposing nulls make ADF-plus-KPSS a useful triangulation strategy, although neither test proves stationarity and both can have low power or size distortion in short samples, near-unit-root processes, or series with breaks. Chrono Stream lets the user select ADF, KPSS, Phillips–Perron, or an ADF–KPSS consensus and caps differencing to avoid an uncontrolled search.

After transformation and differencing, the ACF and PACF provide Box–Jenkins identification evidence, but their approximate significance bands are guides rather than a unique order-selection theorem. Chrono Stream restores both guided and exhaustive/manual order search. Candidate fits are ranked with Akaike's information criterion (Akaike, 1974), Schwarz's Bayesian criterion (Schwarz, 1978), Hannan–Quinn (Hannan & Quinn, 1979), small-sample AICc (Hurvich & Tsai, 1989), or expanding-window validation. Hyndman and Khandakar (2008) established an influential automated differencing and stepwise information-criterion framework; Chrono Stream instead exposes its candidate bounds and diagnostic gates so the decision remains auditable.

Box–Jenkins methodology requires model checking after estimation. Box and Pierce (1970) derived residual-autocorrelation diagnostics, and Ljung and Box (1978) improved the finite-sample approximation of the portmanteau statistic. Chrono Stream additionally offers coefficient Wald z tests, four residual-normality tests (Anderson & Darling, 1952; Jarque & Bera, 1980; Lilliefors, 1967; Shapiro & Wilk, 1965), a zero-mean t test (Student, 1908), Engle's (1982) ARCH LM test, optimizer convergence, and stationarity/invertibility roots. These diagnostics answer different questions and cannot substitute for one another. In particular, failure to reject normality is not proof of Gaussian innovations, while a significant normality test need not invalidate point forecasts. The app therefore provides strict, forecast-oriented, advisory, and custom policies. A strict policy is deliberately demanding: all enabled gates must pass before information criteria rank eligible models, and the user must explicitly authorize a closest-model override if no candidate passes.

ARIMA is most appropriate for a single regularly spaced series whose transformed and differenced dynamics are approximately linear and stable. Its strengths are transparent lag structure, likelihood-based uncertainty, and disciplined residual checking. Its weaknesses include sensitivity to breaks, outliers, missing or irregular timing, excessive differencing, large search spaces, and dependence of intervals on distributional assumptions. A model that passes a battery of tests can still forecast poorly after a regime change, so diagnostic adequacy and rolling-origin predictive performance should be reported together rather than treated as competing definitions of “best.”
""".strip(),
    "sarima": """
Seasonal ARIMA extends the Box–Jenkins ARIMA construction to dependence and integration at a known seasonal period m. Box and Jenkins (1970) formulated multiplicative seasonal models in which a nonseasonal ARIMA(p,d,q) polynomial is combined with seasonal autoregressive, differencing, and moving-average polynomials (P,D,Q)_m. The multiplication creates cross-lag structure rather than two unrelated models. For example, monthly data with m=12 can contain both recent-month dynamics and dependence at lags 12, 24, and beyond. The seasonal period must come from the observation frequency or domain; it is not synonymous with forecast horizon.

Seasonal differencing addresses a seasonal unit root, not every visually seasonal pattern. Hylleberg et al. (1990) developed formal testing for unit roots at seasonal frequencies. Osborn et al. (1988) developed the seasonal-integration regression behind the OCSB decision, while Canova and Hansen (1995) constructed tests with stable seasonality as the null. These tests have different hypotheses and therefore may disagree. Chrono Stream offers OCSB, Canova–Hansen, a seasonal-lag ACF rule, or manual D. In the automatic path, seasonal differencing is considered before regular differencing; this ordering reduces the risk that regular differencing is used to absorb a seasonal unit root. The ACF rule is explicitly labeled a heuristic because its fixed 0.30 floor and approximate sampling band do not constitute a formal seasonal-unit-root test.

The remaining workflow inherits the ARIMA literature. Box–Cox or Yeo–Johnson transformation is fitted before mean-stationarity decisions (Box & Cox, 1964; Yeo & Johnson, 2000). Regular d can be assessed with ADF, KPSS, Phillips–Perron, or a consensus of opposing nulls (Dickey & Fuller, 1979; Kwiatkowski et al., 1992; Phillips & Perron, 1988). Seasonal and nonseasonal ACF/PACF peaks guide P, Q, p, and q but do not determine a unique model. Candidate models are compared with AIC, AICc, BIC, HQIC, or rolling-origin forecast error (Akaike, 1974; Hannan & Quinn, 1979; Hurvich & Tsai, 1989; Schwarz, 1978), after any mandatory diagnostic requirements have been applied.

Diagnostic checking is particularly important because SARIMA can become heavily parameterized. Chrono Stream evaluates convergence, all nonvariance coefficient p-values, AR and MA polynomial roots, standardized-residual mean, one selected normality test, degrees-of-freedom-corrected Ljung–Box or Box–Pierce statistics at multiple lags, and optional ARCH effects (Anderson & Darling, 1952; Box & Pierce, 1970; Engle, 1982; Jarque & Bera, 1980; Lilliefors, 1967; Ljung & Box, 1978; Shapiro & Wilk, 1965; Student, 1908). Seasonal white-noise lags include m and 2m when feasible. Requiring every individual coefficient to be significant and residuals to pass normality is stricter than many forecast-oriented applications, so policy controls allow those gates to be mandatory, advisory, or disabled while keeping the outcome visible.

SARIMA is effective for one dominant, stable seasonal cycle in a sufficiently long, regularly spaced series. It needs enough observations to identify seasonal coefficients and to leave useful degrees of freedom after differencing. It is less suitable for multiple or changing seasonalities, complex holiday effects, abrupt interventions, and large periods relative to sample length. Seasonal over-differencing can induce unnecessary moving-average structure, while an excessive (p,q,P,Q) grid can produce fragile fits. Accordingly, a defensible report should give the transformation, d and D evidence, selected order, search space, selection criterion, parameter and root diagnostics, residual tests with their lags and alpha, and genuine out-of-sample accuracy—not just the final SARIMA label.
""".strip(),
    "x11": """
Seasonal adjustment by Census Method II culminated in X-11, documented by Shiskin et al. (1967). X-11 uses iterative moving-average filters, treatment of extreme observations, trading-day options, and a substantial diagnostic framework to estimate trend-cycle, seasonal, and irregular components. Cleveland and Tiao (1976) later provided a stochastic interpretation of Census Method II filters, clarifying that moving-average seasonal adjustment can be understood in relation to underlying component models. These publications define official X-11 and prevent a common historical error: any decomposition followed by forecasting is not automatically an X-11 implementation.

STL—seasonal-trend decomposition using loess—was introduced by Cleveland et al. (1990) as a different and flexible procedure. STL iteratively applies locally weighted regression smoothers to estimate a trend and a periodically indexed seasonal component, with an optional robust loop that downweights large residuals. It accommodates arbitrary integer seasonal periods and allows the smoothness of trend and seasonality to be controlled. Unlike the full Census X-11 system, STL by itself is a decomposition algorithm, not a complete forecasting model; forecasts require explicit rules for extending components beyond the observed sample.

Chrono Stream accurately labels its feature “STL Decomposition Forecast (X-11-inspired).” It executes robust STL, extrapolates the estimated trend by a local linear fit, and cycles the most recent estimated seasonal pattern. The X-11 inspiration is historical and conceptual—decompose a series into systematic and irregular parts—not software equivalence. This approach is a useful transparent benchmark for stable seasonality and a locally smooth trend. It can fail when the seasonal pattern evolves, multiple seasonal cycles coexist, the endpoint trend is unstable, or future shocks dominate. The residual is not forecast as predictable structure, and uncertainty intervals are empirical rather than an official X-11/X-13 output. A scholarly description should therefore cite Shiskin et al. and Cleveland and Tiao for the X-11 lineage, cite Cleveland et al. for the algorithm actually run, and state the distinction exactly as the app does.
""".strip(),
    "prophet": """
Prophet was introduced by Taylor and Letham (2018) as a practical forecasting system for business time series with strong calendar structure, missing observations, outliers, and trend changes. Its core is a decomposable model in which the observation is represented by a trend, seasonal functions, holiday or event effects, and an error term. The architecture prioritizes analyst-adjustable components and scalable fitting over automated selection from a single classical model family. Taylor and Letham explicitly described both a piecewise linear trend and a saturating logistic trend, automatic changepoint regularization, Fourier seasonal bases, and holiday regressors.

The piecewise trend is related to structural time-series reasoning: Harvey and Shephard (1993) developed structural formulations in which trend and seasonal components have explicit probabilistic roles. Prophet is not identical to those state-space models, but that literature provides an important conceptual foundation for decomposing a series into interpretable latent components. Prophet represents periodic seasonality through partial Fourier sums and uses priors to regularize flexibility. Changepoints permit the growth rate to change, while the prior scale controls whether the fitted trend is smooth or highly adaptive.

Prophet is most useful when timestamps carry meaningful calendar information, history spans the seasonal cycles of interest, and trend changes are more plausible than short-lag autoregressive dynamics. It does not automatically make arbitrary data “forecastable,” and it can extrapolate poorly after unprecedented regime changes. Flexible trend and seasonal components may fit anomalies, while default annual or weekly seasonalities may be inappropriate for the sampling frequency. Chrono Stream uses the Prophet package directly, supplies the dated target series, controls built-in seasonalities based on the data configuration, and returns Prophet uncertainty intervals. Those intervals depend on the package's assumptions about future trend changes and observation noise. A sound analysis should document frequency, enabled seasonalities, changepoint settings, any holiday regressors, and held-out accuracy rather than relying on Prophet's convenience as evidence of validity.
""".strip(),
    "lstm": """
Long short-term memory (LSTM) networks were introduced by Hochreiter and Schmidhuber (1997) to address vanishing or exploding error flow in recurrent neural networks. The memory cell and multiplicative gates created paths along which information and gradients could persist across long delays. Gers et al. (2000) added the forget gate, allowing a cell to reset state that is no longer useful, and Gers et al. (2001) evaluated LSTM in time-series prediction settings. These papers establish LSTM as a recurrent sequence-learning architecture; they do not imply that an LSTM is universally superior to statistical or fixed-window baselines.

An LSTM processes an ordered sequence through a hidden state and cell state. Input, output, and forget gates regulate which new information is written, which stored information is retained, and which state is exposed. For univariate forecasting, a common supervised construction converts the series into overlapping lookback windows and next-value targets. Scaling is usually necessary for stable optimization. A multi-step forecast may be direct, multi-output, sequence-to-sequence, or recursive. Recursive forecasting is simple but creates a distribution shift because predicted values, rather than observed values, become later inputs.

Chrono Stream implements a compact single-layer LSTM trained on normalized univariate rolling windows and recursively feeds back one-step predictions. This makes the architecture accessible and reproducible, but it deliberately omits exogenous variables, probabilistic output, ensembles, and elaborate tuning. LSTM performance is sensitive to lookback, hidden units, initialization, optimizer, epochs, scaling, and sample size. Overlapping windows do not create independent information, so a series that looks “large” after windowing may still contain little historical variation. Neural models also do not remove the need for time-ordered validation; random train–test shuffling would leak future structure. A defensible literature review should therefore present LSTM as a flexible nonlinear learner, explain the gating innovation, state the app's recursive strategy, and compare it against simpler benchmarks on a temporally held-out period.
""".strip(),
    "cnn": """
Convolutional neural networks developed from architectures that exploited local receptive fields and shared feature detectors. Fukushima's neocognitron (1980) provided an influential hierarchical, shift-tolerant precursor. LeCun et al. (1989) trained shared convolutional weights end to end with backpropagation, and LeCun et al. (1998) consolidated the gradient-based convolutional architecture. Although these works focused on spatial patterns, the same operation can slide along time. Borovykh et al. (2017) explicitly developed convolutional architectures for time-series forecasting, demonstrating how causal and dilated filters can learn temporal features.

In a one-dimensional forecasting CNN, kernels convolve over a lag window and learn local motifs such as slopes, pulses, or short cycles. Weight sharing makes the same motif detectable at different positions and typically uses fewer parameters than a fully connected network over the same window. Pooling or dilation can expand the receptive field, after which dense layers map extracted features to forecasts. A plain finite-window CNN has no persistent state beyond its receptive field; long dependencies must fit inside the window or be reached through depth and dilation.

Chrono Stream uses a compact one-dimensional CNN on normalized univariate rolling windows and makes recursive multi-step forecasts. It is intentionally much smaller than the deep dilated architecture studied by Borovykh et al. (2017), so that citation establishes the temporal-convolution approach rather than an exact architectural reproduction. CNNs can model nonlinear local interactions, but results are sensitive to kernel size, lookback, filters, training seed, epochs, and sample size. Recursive feedback compounds error, and a high-capacity network can memorize overlapping training windows. Consequently, the method should be assessed with chronological validation, repeated fits when stochastic variability matters, and direct comparison with moving-average, exponential-smoothing, and ARIMA baselines.
""".strip(),
    "xgboost": """
Gradient boosting constructs a strong predictor by adding weak learners sequentially in the direction that reduces a differentiable loss. Friedman (2001) formulated gradient boosting as function-space optimization, establishing the general statistical learning framework. Chen and Guestrin (2016) introduced XGBoost, combining regularized tree boosting with shrinkage, column and row subsampling, sparsity-aware split finding, and efficient systems design. Time-series forecasting is not a native operation of a decision tree, so an ordered series must first be represented as supervised features such as lags and calendar or exogenous variables.

For a univariate lag model, the feature vector at time t contains y_(t-1),...,y_(t-L), and the target is y_t. Boosted trees partition this lag space and sum piecewise-constant contributions, allowing thresholds and interactions that linear autoregression cannot express. Multi-step strategy is a separate design choice. Ben Taieb et al. (2012) compared recursive and direct approaches and showed that the strategy affects bias, variance, and error propagation. Recursive forecasting estimates one next-step model and feeds each prediction back; direct forecasting trains horizon-specific models; multi-output approaches estimate several horizons jointly.

Chrono Stream trains XGBoost on lagged univariate windows and uses recursive forecasts. It exposes major regularization and tree controls but does not add calendar features or external regressors automatically. The method can capture nonlinear lag interactions and is often strong on medium-sized structured data, yet it cannot extrapolate a smooth numerical trend in the same way as a trend model because trees predict combinations of learned terminal values. Long lookbacks reduce the number of usable training rows, recursive forecasts can settle into fixed patterns, and random splitting would leak temporal information. A responsible report should specify the lag construction, boosting parameters, recursive strategy, chronological validation design, and comparison benchmarks. Friedman (2001) supports the boosting principle, Chen and Guestrin (2016) supports the actual learner, and Ben Taieb et al. (2012) supports explicit treatment of the multi-step strategy.
""".strip(),
    "linear": """
Linear trend forecasting combines the least-squares principle with time as the explanatory variable. Legendre (1805) first published the method of least squares, and Gauss (1809) supplied a probabilistic and astronomical treatment while also asserting earlier use. These works establish least-squares estimation, not a modern time-series forecast method in isolation. Fitting y_t = a + b*t turns that estimation principle into a deterministic extrapolation rule: the slope is the estimated average change per index step and future forecasts extend the same line.

The model is transparent and provides an important benchmark for whether more elaborate methods add value. Under classical independent, equal-variance, correctly specified errors, ordinary least squares has familiar optimality and inferential properties. Time-series residuals commonly violate those assumptions through serial correlation, changing variance, seasonality, and structural breaks. Yule (1926) demonstrated how trending series can exhibit misleading correlation, an enduring warning that a high in-sample R-squared or visually close line is not evidence of a stable forecasting relationship.

Chrono Stream fits observation value against integer time by least squares and extrapolates the fitted line. The index spacing is assumed regular; actual irregular timestamp gaps are not used as unequal durations. The method contains no seasonal or autoregressive component and no mechanism for a slope change after the sample endpoint. It is therefore most defensible as a descriptive baseline over horizons where a roughly constant increment is plausible. A complete analysis should inspect residual structure, sensitivity to the fitted start date, breaks, and held-out forecast error. If the linear trend wins, its simplicity is an advantage; if it loses, it still provides a meaningful reference against which the incremental complexity of other methods can be judged.
""".strip(),
    "quadratic": """
Quadratic trend forecasting is a polynomial least-squares projection rather than a separately invented stochastic time-series method. Legendre (1805) established least squares, and Gergonne (1815) developed polynomial least-squares interpolation and approximation in an explicit algebraic form. Applying those ideas to time produces y_t = a*t^2 + b*t + c. The first difference changes approximately linearly with time and the second difference is approximately constant, giving the curve one direction of acceleration or deceleration over its domain.

The added curvature can fit a smooth bend that a straight line misses, but polynomial extrapolation is dominated by its highest-degree term. Small changes in the estimated quadratic coefficient can therefore create large long-horizon changes, reversals, or impossible values. The apparent curvature can also be an artifact of the chosen time origin, a short sample, an outlier, seasonality, or a structural break. Yule's (1926) analysis of spurious relationships among trending series reinforces the distinction between describing the observed path and identifying a stable dynamic process.

Chrono Stream fits a degree-two polynomial to regularly spaced observation indices and evaluates it at future indices. It does not recursively update values and does not model serially dependent errors, recurring seasonality, or a saturation boundary. The method is suitable as a cautious short-horizon benchmark when domain knowledge supports smooth acceleration, but it should rarely be accepted from in-sample fit alone. Users should plot the extrapolation, test sensitivity to the training window, compare it with a linear trend, and evaluate it chronologically. The literature supports the least-squares polynomial machinery; it does not justify interpreting every estimated parabola as a persistent law of the underlying phenomenon.
""".strip(),
    "exponential": """
Exponential trend forecasting assumes multiplicative growth or decline of the form y_t = A*exp(b*t), so the expected proportional change is constant under the deterministic curve. Malthus (1798) supplied an influential early domain formulation of exponential population growth, while Legendre's (1805) least-squares principle provides the fitting foundation. The curve is linearized as log(y_t) = a + b*t + error and therefore requires strictly positive observations. This model should not be confused with exponential smoothing: exponential trend describes a functional growth shape, whereas exponential smoothing describes geometrically declining weights or evolving states.

Log-scale least squares estimates the center of log(y), and simply exponentiating a fitted log mean generally targets a conditional median on the original scale rather than its conditional mean. Duan (1983) developed the nonparametric smearing estimator to correct retransformation bias without requiring normally distributed log errors, and Miller (1984) analyzed bias in retransformed log-linear models. These contributions are essential when an app reports original-scale mean forecasts rather than only median-like back-transformations.

Chrono Stream fits a linear trend to logged positive values, estimates Duan's smearing factor from training residuals, and multiplies exponentiated predictions by that factor. This is faithful to the cited retransformation literature. The model is useful when percentage growth is approximately stable over the forecast horizon, but compounding makes long-range results extremely sensitive to the estimated slope. It has no saturation, seasonal, autoregressive, or break component; a short-lived surge can generate explosive forecasts. Smearing also assumes that the retransformation factor is sufficiently stable across the predictor range. A defensible report should distinguish mean from median forecasts, state the positivity restriction and smearing factor, inspect log-scale residuals, and validate the compounding trajectory out of sample.
""".strip(),
    "logarithmic": """
The logarithmic trend y_t = a*log(t) + b combines least-squares curve fitting with an imposed diminishing-change shape. Legendre (1805) supplies the estimation foundation. Fechner (1860) is an early defining scientific use of a logarithmic response law in psychophysics, but it is not an origin paper for time-series forecasting. Accordingly, the method should be described as a deterministic curve-projection benchmark, not attributed to a single inventor of “logarithmic forecasting.”

Equal multiplicative changes in the positive time index produce equal additive changes in the fitted response, and the instantaneous slope a/t shrinks in magnitude. The curve can therefore represent rapid early growth followed by continuing but progressively smaller gains, or the corresponding pattern of decline. Starting the index at one avoids log(0), but the fitted curve depends on that origin: shifting the historical start date changes every transformed predictor and can materially change the extrapolation.

Chrono Stream regresses the observed value on log(1),...,log(n) and evaluates the curve at future integer indices. It does not estimate a finite carrying capacity, an S-shaped transition, seasonal effects, or serial dependence. Yule (1926) showed why shared trend can make deterministic relationships look stronger than their stochastic basis warrants. The logarithmic curve is therefore most useful as an interpretable baseline when domain knowledge supports diminishing increments and the forecast horizon is modest. Users should compare alternative time origins and training windows, inspect residual autocorrelation, and validate forecasts chronologically. A close historical fit alone is not evidence that the diminishing pattern will persist.
""".strip(),
}

