"""Scholarly reviews for the holdout accuracy measures reported by Chrono Stream."""

from __future__ import annotations


METRIC_LITERATURE_REVIEWS: dict[str, str] = {
    "MAE": """
Mean absolute error (MAE) averages |y_t - ŷ_t| over the forecast cases. Its mathematical appeal is that every error enters linearly: doubling one absolute miss doubles that case's contribution. This makes MAE directly interpretable in the response unit and less dominated by a few large errors than a squared-error measure. Willmott and Matsuura (2005) argued that this direct relation to average error magnitude makes MAE a more transparent description of average model error than RMSE. That argument does not make MAE universally preferable; it identifies the kind of discrepancy MAE summarizes.

The loss function also determines the point forecast being rewarded. Gneiting (2011) placed point-forecast evaluation in a decision-theoretic framework: absolute-error loss is consistent for a conditional median, whereas squared-error loss is consistent for a conditional mean. Consequently, an MAE ranking is not a neutral report detached from the forecasting target. On a skewed or intermittent count distribution, a median-optimal forecast can be lower than a mean-optimal forecast and may even be zero. Whether that is desirable depends on the operational cost of under- and over-forecasting.

MAE is scale dependent. It is excellent for comparing methods on the same series and holdout because all methods face the same unit and observations, but its raw values should not be averaged across unrelated series with very different magnitudes without a deliberate weighting scheme. Hewamalage, Ackermann, and Bergmeir (2023) emphasize matching the error measure to the data and decision, using chronological out-of-sample evaluation, and reporting more than one measure when the implied loss functions matter. Chrono Stream therefore presents MAE beside squared, percentage, and benchmark-scaled measures rather than declaring it a universal winner.
""".strip(),
    "RMSE": """
Root mean squared error (RMSE) is the square root of the mean squared forecast error. Squaring makes the score respond more than proportionally to a large miss, and the final square root returns the summary to the response unit. On a fixed set of forecast cases, RMSE and MSE produce the same ranking because the square root is monotone. The practical distinction from MAE is therefore not the unit alone but the stronger influence assigned to the tail of the error-magnitude distribution.

Squared-error evaluation has a decision-theoretic meaning. Gneiting (2011) showed that squared error is consistent for the conditional mean, while absolute error is consistent for the conditional median. RMSE can therefore be appropriate when the forecast is intended to estimate a conditional mean and large misses deserve disproportionate cost. Conversely, calling RMSE a generic “average error” can be misleading. Willmott and Matsuura (2005) showed that RMSE changes with both average absolute error and the variability of the error magnitudes, and warned against interpreting it as though it were simply a typical absolute deviation.

RMSE is scale dependent and can be unstable when a short holdout contains one exceptional event. It is still useful for comparing models evaluated on exactly the same series and periods, which is the situation in Chrono Stream's comparison page. Armstrong and Collopy (1992) found that rankings and conclusions can depend materially on the selected accuracy measure, particularly when results are generalized across series. Chrono Stream retains RMSE as its default same-series ordering criterion, but places MAE, MASE, RMSSE, MAPE, sMAPE, and WAPE alongside it so users can see whether a ranking is driven by squared-loss sensitivity.
""".strip(),
    "MAPE": """
Mean absolute percentage error (MAPE) averages 100|y_t - ŷ_t|/|y_t|. Its attraction is communicative: for strictly positive, meaningfully ratio-scaled observations, the result resembles an average percentage miss and is independent of the measurement unit. MAPE became common in empirical forecasting comparisons, but Armstrong and Collopy (1992) and Makridakis (1993) showed that accuracy-measure choice changes method rankings and that percentage summaries require careful interpretation rather than automatic use.

The denominator creates MAPE's central defects. A zero actual makes an individual absolute percentage error undefined, while an actual close to zero can dominate the mean. Deleting zero-actual cases does not repair the definition; it silently changes the evaluated sample and can make a zero-heavy forecast look better by omitting precisely the difficult periods. Hyndman and Koehler (2006) catalogued these degeneracies and proposed benchmark-scaled errors as a more generally applicable alternative. MAPE is also unsuitable for interval or signed data where zero lacks a meaningful ratio interpretation. Its loss geometry can favor systematically low point forecasts for skewed positive outcomes, so the smallest MAPE need not identify the best conditional-mean forecast.

Chrono Stream reports MAPE only when every finite holdout actual is nonzero. If any evaluated actual equals zero, the result is N/A; no term is discarded and no epsilon is inserted into the denominator. Near-zero nonzero actuals remain mathematically defined but can produce very large values, which is a warning about the measure rather than a software error. MAPE is therefore retained for familiar interpretation on suitable positive series, but it is not the primary metric for intermittent demand. MASE, RMSSE, WAPE, MAE, and RMSE provide complementary views with their own disclosed assumptions.
""".strip(),
    "sMAPE": """
The symmetric mean absolute percentage error used by Chrono Stream averages 200|y_t - ŷ_t|/(|y_t| + |ŷ_t|). This common version is bounded between 0% and 200% and treats the actual and forecast symmetrically when their positions in the formula are exchanged. Makridakis (1993) advanced a symmetric percentage formulation in response to concerns about conventional percentage errors, and the M3 competition later used sMAPE as a prominent cross-series accuracy measure (Makridakis & Hibon, 2000).

The name “symmetric” does not remove all asymmetry relevant to forecasting decisions. Goodwin and Lawton (1999) demonstrated that modified or symmetric APE formulations can treat over- and under-forecasts with equal absolute errors differently and can display unintuitive behavior for large errors. The denominator also contains the forecast, so changing a forecast changes both numerator and scale. Values near zero remain influential, negative observations complicate percentage interpretation, and multiple formulas called sMAPE exist with ranges of 0–100 or 0–200. A reported value is therefore reproducible only when the exact equation and zero convention are stated.

Chrono Stream uses absolute values in the denominator and the 0–200% convention. When both actual and forecast are exactly zero, their contribution is defined as 0% because the prediction is exact; when only one is zero, the contribution is 200%. This prevents joint-zero periods from being silently removed, but it is an explicit software convention for the otherwise indeterminate 0/0 term. sMAPE remains useful as a bounded secondary percentage view, not proof that the ranking is unbiased or suitable for the operational loss faced by the user.
""".strip(),
    "MASE": """
Hyndman and Koehler (2006) proposed mean absolute scaled error (MASE) to avoid the zero and scale problems of percentage errors while permitting comparisons across series. The holdout MAE is divided by the in-sample MAE of a simple benchmark. For a nonseasonal series the benchmark differences are |y_t-y_{t-1}|; for a seasonal series they can be |y_t-y_{t-m}|. The denominator is computed from observations available before the forecast origin, so the holdout outcomes do not define their own scale.

MASE is dimensionless and usually finite when percentage errors are not. A value below one means the evaluated holdout MAE is smaller than the training benchmark's average absolute lag-m naive error; when m=1 this is the ordinary one-step naive scale, while m>1 uses a seasonal-lag scale. A value above one means it is larger. This is a scale comparison, not a direct claim that the fitted model beat a separately evaluated naive forecast on the same holdout. Structural change can make the historical benchmark denominator unrepresentative, and an all-constant training series gives zero naive error, leaving MASE undefined. The seasonal lag must also reflect a real cycle rather than being selected after seeing holdout accuracy.

The absolute-error numerator means MASE retains MAE's conditional-median orientation. Hewamalage, Ackermann, and Bergmeir (2023) stress that scaled measures, benchmark choice, nonstationarity, and evaluation design must be reported together. Chrono Stream uses only the pre-holdout training observations for its denominator and uses the configured metric scale period m for every compared model. It returns N/A rather than substituting another lag when fewer than m+1 training observations exist or when the benchmark denominator is zero. This makes the comparison leakage-safe and reproducible while keeping the limitation visible.
""".strip(),
    "RMSSE": """
Root mean squared scaled error (RMSSE) replaces the absolute errors in MASE with squared errors. It is the square root of holdout mean squared error divided by the training mean squared naive-difference error. Makridakis, Spiliotis, and Assimakopoulos (2022) used RMSSE as the per-series foundation of the M5 Accuracy competition's weighted score, motivated in part by thousands of intermittent retail-demand series containing zeros. Like MASE, the scaling avoids division by each individual holdout actual.

RMSSE combines benchmark scaling with squared-loss behavior. Values below one indicate that holdout squared error is lower than the benchmark's average training squared difference, while values above one indicate the reverse. Squaring gives large misses extra influence and aligns the score with a conditional-mean target, an important distinction from MASE's absolute-loss orientation (Gneiting, 2011). RMSSE is undefined when the training benchmark has no squared error, and its magnitude can change when a trend, regime change, or inappropriate seasonal lag makes historical naive differences a poor scale for the forecast period.

Chrono Stream follows the mathematical RMSSE construction but does not claim to reproduce the complete M5 competition score. M5 used a nonseasonal lag-one denominator, active-sales handling, cross-series aggregation, and economic weights. Chrono Stream evaluates one series, uses all pre-holdout training observations, and applies the user-configured scale lag m consistently across saved models; it does not trim leading zero-demand periods or calculate WRMSSE. If the requested lag cannot be formed or its squared-difference mean is zero, RMSSE is shown as N/A. The exact distinction is recorded so an app result is not mislabeled as an M5 leaderboard score.
""".strip(),
    "WAPE": """
Weighted absolute percentage error (WAPE) is 100 times the sum of absolute forecast errors divided by the sum of absolute actual values. On a nonnegative series with a common evaluation window it is algebraically the MAE divided by the mean actual. Kolassa and Schütz (2007) described this construction as the MAD/Mean ratio and showed that it can be viewed as an actual-magnitude-weighted alternative to averaging individual percentage errors. Individual zero actuals are therefore allowed as long as the aggregate denominator is nonzero.

WAPE is easier to compute on intermittent demand than MAPE because it performs one division after aggregation rather than dividing at every zero-prone period. It is not failure-proof. An all-zero holdout has a zero denominator, a large-volume period carries more weight than a small-volume period, and temporal aggregation can conceal whether demand was forecast in the correct period. The absolute-error numerator retains a conditional-median orientation and can reward low or zero forecasts on sufficiently intermittent count distributions even when an inventory decision targets mean demand. WAPE also scales by the evaluation outcomes themselves, so its value across windows can shift with trend or changing level independently of model quality.

Chrono Stream uses sums of absolute actuals, extending the nonnegative MAD/Mean formula to signed series without cancellation in the denominator. For nonnegative demand the formulas coincide. If the holdout's total absolute actual is zero, WAPE is N/A rather than infinite or forced to zero. WAPE is reported as a secondary aggregate percentage, not as a replacement for a chronological plot, a naive benchmark, MASE/RMSSE, or domain costs. Hewamalage, Ackermann, and Bergmeir (2023) likewise emphasize that no single error measure is robust under every data characteristic and decision target.
""".strip(),
}
