[theme]
# Primary accent color for interactive elements.
primaryColor="#6082B6"

# Background color for the main content area.
backgroundColor="#15173c"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor="#252526"

# Color used for almost all text.
textColor="#FFFFFF"
font="sans serif"

[client]
toolbarMode = "minimal"